// Copyright 2026 francis and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type AnalyzableQuestion struct {
	DistinctUserCount string `json:"distinct_user_count"`
	Id                string `json:"id"`
	Options           string `json:"options"`
	Qtype             string `json:"qtype"`
	Question          string `json:"question"`
	QuestionNumber    string `json:"question_number"`
	ResponseCount     string `json:"response_count"`
	Scale             string `json:"scale"`
}

type AnalyzableQuestionsOut struct {
	Category  string          `json:"category"`
	Questions json.RawMessage `json:"questions"`
	StudyId   string          `json:"study_id"`
}

type CapturedVariableOut struct {
	Name       string `json:"name"`
	NodeId     string `json:"node_id"`
	NodeVisit  int    `json:"node_visit"`
	Producer   string `json:"producer"`
	QuestionId string `json:"question_id"`
	Source     string `json:"source"`
	UpdatedAt  string `json:"updated_at"`
	Value      string `json:"value"`
	ValueType  string `json:"value_type"`
}

type Centroid struct {
	Label string  `json:"label"`
	X     float64 `json:"x"`
	Y     float64 `json:"y"`
}

type CharacteristicQuestionCreate struct {
	Options         json.RawMessage `json:"options"`
	Question        string          `json:"question"`
	QuestionType    string          `json:"question_type"`
	SlotDescription string          `json:"slot_description"`
	Variable        string          `json:"variable"`
}

type CharacteristicQuestionOut struct {
	Id              string          `json:"id"`
	Options         json.RawMessage `json:"options"`
	Question        string          `json:"question"`
	QuestionNumber  int             `json:"question_number"`
	QuestionType    string          `json:"question_type"`
	SlotDescription string          `json:"slot_description"`
	Variable        string          `json:"variable"`
}

type CharacteristicQuestionUpdate struct {
	Options         string `json:"options"`
	Question        string `json:"question"`
	QuestionType    string `json:"question_type"`
	SlotDescription string `json:"slot_description"`
	Variable        string `json:"variable"`
}

type CharacteristicValueOut struct {
	Value    string `json:"value"`
	Variable string `json:"variable"`
}

type CharacteristicsOut struct {
	Questions json.RawMessage `json:"questions"`
	Settings  json.RawMessage `json:"settings"`
}

type CharacteristicsSettingsOut struct {
	Anonymous bool `json:"anonymous"`
	Enabled   bool `json:"enabled"`
}

type CharacteristicsSettingsSet struct {
	Anonymous bool `json:"anonymous"`
	Enabled   bool `json:"enabled"`
}

type ClusterPoints struct {
	Analysis         string          `json:"analysis"`
	Name             string          `json:"name"`
	ParticipantNames string          `json:"participant_names"`
	Text             json.RawMessage `json:"text"`
	X                json.RawMessage `json:"x"`
	Y                json.RawMessage `json:"y"`
}

type ClusterRequest struct {
	NClusters      int    `json:"n_clusters"`
	QuestionId     string `json:"question_id"`
	QuestionNumber string `json:"question_number"`
}

type ClusteringOut struct {
	Centroids      json.RawMessage `json:"centroids"`
	DataPoints     json.RawMessage `json:"data_points"`
	Exists         bool            `json:"exists"`
	NClusters      string          `json:"n_clusters"`
	QuestionId     string          `json:"question_id"`
	QuestionNumber string          `json:"question_number"`
	RunId          string          `json:"run_id"`
	Thinking       string          `json:"thinking"`
	Timestamp      string          `json:"timestamp"`
}

type CreditBalanceOut struct {
	AvailableCredits float64 `json:"available_credits"`
	BaseLimit        float64 `json:"base_limit"`
	CreditsReserved  float64 `json:"credits_reserved"`
	CreditsUsed      float64 `json:"credits_used"`
	IsTrialActive    bool    `json:"is_trial_active"`
	NetAvailable     float64 `json:"net_available"`
	PurchasedCredits float64 `json:"purchased_credits"`
	RolloverCredits  float64 `json:"rollover_credits"`
	TrialCreditsUsed float64 `json:"trial_credits_used"`
}

type DecisionOutcomeOut struct {
	ChosenNodeId string          `json:"chosen_node_id"`
	Classes      json.RawMessage `json:"classes"`
	DecidedAt    string          `json:"decided_at"`
	Error        string          `json:"error"`
	MatchedClass string          `json:"matched_class"`
	Mode         string          `json:"mode"`
	NodeId       string          `json:"node_id"`
	NodeVisit    int             `json:"node_visit"`
	RawLabel     string          `json:"raw_label"`
	UsedDefault  bool            `json:"used_default"`
}

type EmbedKeyCreate struct {
	AllowedOrigins   json.RawMessage `json:"allowed_origins"`
	MetadataMaxBytes string          `json:"metadata_max_bytes"`
	StudyId          string          `json:"study_id"`
}

type EmbedKeyListOut struct {
	Keys json.RawMessage `json:"keys"`
}

type EmbedKeyUpdate struct {
	AllowedOrigins   string `json:"allowed_origins"`
	MetadataMaxBytes string `json:"metadata_max_bytes"`
	Status           string `json:"status"`
}

type EmbedMetadataItem struct {
	Key        string `json:"key"`
	Provenance string `json:"provenance"`
	Value      string `json:"value"`
}

type EmbedSnippetOut struct {
	SignedSnippet string `json:"signed_snippet"`
	Snippet       string `json:"snippet"`
	StudyId       string `json:"study_id"`
	WidgetSrc     string `json:"widget_src"`
}

type EthicsCheck struct {
	Issues json.RawMessage `json:"issues"`
	Passed bool            `json:"passed"`
}

type FlowCheckError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	NodeId  string `json:"node_id"`
}

type FlowDocument struct {
	Edges json.RawMessage `json:"edges"`
	Nodes json.RawMessage `json:"nodes"`
}

type FlowEdge struct {
	Class     string `json:"class"`
	Condition string `json:"condition"`
	Default   bool   `json:"default"`
	From      string `json:"from"`
	Priority  int    `json:"priority"`
	To        string `json:"to"`
}

type FlowNode struct {
	After       string          `json:"after"`
	Before      string          `json:"before"`
	Config      json.RawMessage `json:"config"`
	Id          string          `json:"id"`
	MaxRevisits string          `json:"max_revisits"`
	Type        string          `json:"type"`
}

type FlowSignalOut struct {
	Enabled       bool   `json:"enabled"`
	Method        string `json:"method"`
	SignalType    string `json:"signal_type"`
	SigningSecret string `json:"signing_secret"`
	StepId        string `json:"step_id"`
	UpdatedAt     string `json:"updated_at"`
	Url           string `json:"url"`
}

type FlowSignalsOut struct {
	GraphVersion int             `json:"graph_version"`
	Signals      json.RawMessage `json:"signals"`
	StudyId      string          `json:"study_id"`
}

type GraphCheckOut struct {
	Compiled     string          `json:"compiled"`
	Errors       json.RawMessage `json:"errors"`
	GraphVersion int             `json:"graph_version"`
	Saved        bool            `json:"saved"`
	Valid        bool            `json:"valid"`
}

type GraphCheckRequest struct {
	Flow string `json:"flow"`
}

type GraphModeOut struct {
	InterviewMode string `json:"interview_mode"`
	IsActive      bool   `json:"is_active"`
	StudyId       string `json:"study_id"`
}

type GraphOut struct {
	Errors        json.RawMessage `json:"errors"`
	Flow          string          `json:"flow"`
	GraphVersion  int             `json:"graph_version"`
	HasCompiledIr bool            `json:"has_compiled_ir"`
	InterviewMode string          `json:"interview_mode"`
	IsActive      bool            `json:"is_active"`
	StudyId       string          `json:"study_id"`
}

type GraphPatch struct {
	ExpectedGraphVersion string          `json:"expected_graph_version"`
	Ops                  json.RawMessage `json:"ops"`
}

type GraphReplace struct {
	ExpectedGraphVersion string          `json:"expected_graph_version"`
	Flow                 json.RawMessage `json:"flow"`
}

type HTTPValidationError struct {
	Detail json.RawMessage `json:"detail"`
}

type InterviewDetailListOut struct {
	ExternalParticipantId string          `json:"external_participant_id"`
	Interviews            json.RawMessage `json:"interviews"`
	StudyId               string          `json:"study_id"`
	Total                 int             `json:"total"`
}

type InterviewDetailOut struct {
	Characteristics       json.RawMessage `json:"characteristics"`
	Completed             string          `json:"completed"`
	EmbedMetadata         json.RawMessage `json:"embed_metadata"`
	EndTime               string          `json:"end_time"`
	ExternalParticipantId string          `json:"external_participant_id"`
	Id                    string          `json:"id"`
	MessageCount          int             `json:"message_count"`
	ParticipantId         string          `json:"participant_id"`
	ParticipantName       string          `json:"participant_name"`
	Qualifications        json.RawMessage `json:"qualifications"`
	Referrer              string          `json:"referrer"`
	Simulated             bool            `json:"simulated"`
	StartTime             string          `json:"start_time"`
	StudyId               string          `json:"study_id"`
	TerminationReason     string          `json:"termination_reason"`
	Variables             json.RawMessage `json:"variables"`
	WebSource             string          `json:"web_source"`
}

type InterviewEffectsOut struct {
	ExternalParticipantId string          `json:"external_participant_id"`
	Fetches               json.RawMessage `json:"fetches"`
	InterviewId           string          `json:"interview_id"`
	Signals               json.RawMessage `json:"signals"`
	Simulated             bool            `json:"simulated"`
	StudyId               string          `json:"study_id"`
	WebSource             string          `json:"web_source"`
}

type InterviewListOut struct {
	Interviews json.RawMessage `json:"interviews"`
	Limit      int             `json:"limit"`
	Offset     int             `json:"offset"`
	StudyId    string          `json:"study_id"`
	Total      int             `json:"total"`
}

type InterviewSummary struct {
	Completed             string `json:"completed"`
	EndTime               string `json:"end_time"`
	ExternalParticipantId string `json:"external_participant_id"`
	Id                    string `json:"id"`
	ParticipantId         string `json:"participant_id"`
	ParticipantName       string `json:"participant_name"`
	Referrer              string `json:"referrer"`
	Simulated             bool   `json:"simulated"`
	StartTime             string `json:"start_time"`
	TerminationReason     string `json:"termination_reason"`
	WebSource             string `json:"web_source"`
}

type InterviewTranscript struct {
	Completed             string          `json:"completed"`
	ExternalParticipantId string          `json:"external_participant_id"`
	InterviewId           string          `json:"interview_id"`
	Messages              json.RawMessage `json:"messages"`
	ParticipantId         string          `json:"participant_id"`
	ParticipantName       string          `json:"participant_name"`
	Simulated             bool            `json:"simulated"`
	StartTime             string          `json:"start_time"`
	Variables             json.RawMessage `json:"variables"`
	WebSource             string          `json:"web_source"`
}

type LanguageIssues struct {
	Clarity  string `json:"clarity"`
	Grammar  string `json:"grammar"`
	Spelling string `json:"spelling"`
}

type NodeFetchOut struct {
	CreatedAt   string `json:"created_at"`
	Data        string `json:"data"`
	Error       string `json:"error"`
	Method      string `json:"method"`
	NodeId      string `json:"node_id"`
	NodeVisit   int    `json:"node_visit"`
	Ok          bool   `json:"ok"`
	RequestBody string `json:"request_body"`
	StatusCode  string `json:"status_code"`
	Url         string `json:"url"`
}

type OptimalClustersOut struct {
	Inertias json.RawMessage `json:"inertias"`
	KValues  json.RawMessage `json:"k_values"`
	OptimalK int             `json:"optimal_k"`
}

type OptimalClustersRequest struct {
	QuestionId     string `json:"question_id"`
	QuestionNumber string `json:"question_number"`
}

type OptionCount struct {
	Count  int    `json:"count"`
	Option string `json:"option"`
}

type OptionsResponsesOut struct {
	Counts     json.RawMessage `json:"counts"`
	QuestionId string          `json:"question_id"`
	StudyId    string          `json:"study_id"`
}

type PatchOp struct {
	After       string `json:"after"`
	Before      string `json:"before"`
	Class       string `json:"class"`
	Condition   string `json:"condition"`
	Config      string `json:"config"`
	Default     string `json:"default"`
	Edge        string `json:"edge"`
	From        string `json:"from"`
	Id          string `json:"id"`
	MaxRevisits string `json:"max_revisits"`
	Node        string `json:"node"`
	Op          string `json:"op"`
	Priority    string `json:"priority"`
	To          string `json:"to"`
}

type PersonaCreate struct {
	Content string `json:"content"`
	Source  string `json:"source"`
}

type PersonaGenerateOut struct {
	Personas json.RawMessage `json:"personas"`
	Saved    bool            `json:"saved"`
	StudyId  string          `json:"study_id"`
}

type PersonaGenerateRequest struct {
	Count int  `json:"count"`
	Save  bool `json:"save"`
}

type PersonaListOut struct {
	Personas json.RawMessage `json:"personas"`
	StudyId  string          `json:"study_id"`
	Total    int             `json:"total"`
}

type PersonaOut struct {
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
	Id        string `json:"id"`
	Preview   string `json:"preview"`
	Source    string `json:"source"`
	StudyId   string `json:"study_id"`
	UpdatedAt string `json:"updated_at"`
}

type PersonaUpdate struct {
	Content string `json:"content"`
}

type ProjectCreate struct {
	Description string `json:"description"`
	Name        string `json:"name"`
}

type ProjectListOut struct {
	Projects json.RawMessage `json:"projects"`
}

type ProjectOut struct {
	Description string `json:"description"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	StudyCount  int    `json:"study_count"`
}

type ProjectUpdate struct {
	Description string `json:"description"`
	Name        string `json:"name"`
}

type QualificationOut struct {
	Answer      string `json:"answer"`
	IsQualified string `json:"is_qualified"`
	Question    string `json:"question"`
}

type QuestionCreate struct {
	ExpectedImage string `json:"expected_image"`
	Explanation   string `json:"explanation"`
	FollowUp      bool   `json:"follow_up"`
	Groups        string `json:"groups"`
	MaxSelect     string `json:"max_select"`
	MaxTurns      string `json:"max_turns"`
	MinSelect     string `json:"min_select"`
	MinTurns      string `json:"min_turns"`
	Options       string `json:"options"`
	Qtype         string `json:"qtype"`
	Question      string `json:"question"`
	Scale         string `json:"scale"`
	Slots         string `json:"slots"`
}

type QuestionImageOut struct {
	GcsUrl   string `json:"gcs_url"`
	Id       string `json:"id"`
	Label    string `json:"label"`
	Position int    `json:"position"`
}

type QuestionListOut struct {
	Questions json.RawMessage `json:"questions"`
	StudyId   string          `json:"study_id"`
}

type QuestionOrder struct {
	QuestionIds json.RawMessage `json:"question_ids"`
}

type QuestionOut struct {
	ExpectedImage  string          `json:"expected_image"`
	Explanation    string          `json:"explanation"`
	FollowUp       string          `json:"follow_up"`
	Groups         string          `json:"groups"`
	Id             string          `json:"id"`
	Images         json.RawMessage `json:"images"`
	MaxSelect      string          `json:"max_select"`
	MaxTurns       string          `json:"max_turns"`
	MinSelect      string          `json:"min_select"`
	MinTurns       string          `json:"min_turns"`
	Options        string          `json:"options"`
	Question       string          `json:"question"`
	QuestionNumber int             `json:"question_number"`
	Scale          string          `json:"scale"`
	Slots          string          `json:"slots"`
	Type           string          `json:"type"`
}

type QuestionUpdate struct {
	ExpectedImage string `json:"expected_image"`
	Explanation   string `json:"explanation"`
	FollowUp      string `json:"follow_up"`
	Groups        string `json:"groups"`
	MaxSelect     string `json:"max_select"`
	MaxTurns      string `json:"max_turns"`
	MinSelect     string `json:"min_select"`
	MinTurns      string `json:"min_turns"`
	Options       string `json:"options"`
	Qtype         string `json:"qtype"`
	Question      string `json:"question"`
	Scale         string `json:"scale"`
	Slots         string `json:"slots"`
}

type QuestionValidation struct {
	HasIssues      bool            `json:"has_issues"`
	LanguageIssues json.RawMessage `json:"language_issues"`
	Number         int             `json:"number"`
	QuestionId     string          `json:"question_id"`
	Redundancy     json.RawMessage `json:"redundancy"`
	Suggestions    string          `json:"suggestions"`
}

type RecruitmentOut struct {
	CharacteristicsEnabled     bool   `json:"characteristics_enabled"`
	CompletedInterviews        int    `json:"completed_interviews"`
	MaxResponses               string `json:"max_responses"`
	ParticipationUrl           string `json:"participation_url"`
	QuotaRemaining             string `json:"quota_remaining"`
	RedirectUrl                string `json:"redirect_url"`
	RedirectUrlWarning         string `json:"redirect_url_warning"`
	ScreeningEnabled           bool   `json:"screening_enabled"`
	ShortParticipationUrl      string `json:"short_participation_url"`
	ShortUrlSlug               string `json:"short_url_slug"`
	ShortVideoParticipationUrl string `json:"short_video_participation_url"`
	ShortVoiceParticipationUrl string `json:"short_voice_participation_url"`
	StudyId                    string `json:"study_id"`
	VideoParticipationUrl      string `json:"video_participation_url"`
	VoiceParticipationUrl      string `json:"voice_participation_url"`
}

type RecruitmentUpdate struct {
	ClearMaxResponses bool   `json:"clear_max_responses"`
	MaxResponses      string `json:"max_responses"`
	RedirectUrl       string `json:"redirect_url"`
	ShortUrlSlug      string `json:"short_url_slug"`
}

type RedundancyCheck struct {
	Description  string          `json:"description"`
	IsRedundant  bool            `json:"is_redundant"`
	OverlapsWith json.RawMessage `json:"overlaps_with"`
}

type ScaleConfig struct {
	MaxLabel string `json:"maxLabel"`
	MaxScale int    `json:"maxScale"`
	MinLabel string `json:"minLabel"`
	MinScale int    `json:"minScale"`
}

type ScaleResponsesOut struct {
	Counts     json.RawMessage `json:"counts"`
	QuestionId string          `json:"question_id"`
	StudyId    string          `json:"study_id"`
}

type ScreeningOut struct {
	Questions json.RawMessage `json:"questions"`
	Settings  json.RawMessage `json:"settings"`
}

type ScreeningQuestionCreate struct {
	AcceptableOptions json.RawMessage `json:"acceptable_options"`
	Options           json.RawMessage `json:"options"`
	Question          string          `json:"question"`
}

type ScreeningQuestionOut struct {
	AcceptableOptions json.RawMessage `json:"acceptable_options"`
	Id                string          `json:"id"`
	Options           json.RawMessage `json:"options"`
	Question          string          `json:"question"`
	QuestionNumber    int             `json:"question_number"`
}

type ScreeningQuestionUpdate struct {
	AcceptableOptions string `json:"acceptable_options"`
	Options           string `json:"options"`
	Question          string `json:"question"`
}

type ScreeningSettingsOut struct {
	DisqualificationMessage string `json:"disqualification_message"`
	Enabled                 bool   `json:"enabled"`
	RedirectUrl             string `json:"redirect_url"`
	RedirectUrlWarning      string `json:"redirect_url_warning"`
}

type ScreeningSettingsSet struct {
	DisqualificationMessage string `json:"disqualification_message"`
	Enabled                 bool   `json:"enabled"`
	RedirectUrl             string `json:"redirect_url"`
}

type SearchHit struct {
	Content               string          `json:"content"`
	ExternalParticipantId string          `json:"external_participant_id"`
	InterviewId           string          `json:"interview_id"`
	MessageId             string          `json:"message_id"`
	NodeId                string          `json:"node_id"`
	ParticipantId         string          `json:"participant_id"`
	ParticipantName       string          `json:"participant_name"`
	QuestionId            string          `json:"question_id"`
	QuestionNumber        string          `json:"question_number"`
	Score                 float64         `json:"score"`
	Sources               json.RawMessage `json:"sources"`
	Timestamp             string          `json:"timestamp"`
}

type SearchOut struct {
	Hits    json.RawMessage `json:"hits"`
	Mode    string          `json:"mode"`
	Query   string          `json:"query"`
	StudyId string          `json:"study_id"`
}

type SignalDeliveryOut struct {
	Attempt     int    `json:"attempt"`
	CreatedAt   string `json:"created_at"`
	DryRun      bool   `json:"dry_run"`
	Error       string `json:"error"`
	EventType   string `json:"event_type"`
	MsgId       string `json:"msg_id"`
	NodeId      string `json:"node_id"`
	NodeVisit   int    `json:"node_visit"`
	RequestBody string `json:"request_body"`
	StatusCode  string `json:"status_code"`
	Success     bool   `json:"success"`
	UpdatedAt   string `json:"updated_at"`
	Url         string `json:"url"`
}

type SimulationListOut struct {
	Simulations json.RawMessage `json:"simulations"`
	StudyId     string          `json:"study_id"`
	Total       int             `json:"total"`
}

type SimulationOut struct {
	CreditsUsed    string `json:"credits_used"`
	DeliverSignals bool   `json:"deliver_signals"`
	Error          string `json:"error"`
	Id             string `json:"id"`
	InterviewId    string `json:"interview_id"`
	ModelId        string `json:"model_id"`
	ModelProvider  string `json:"model_provider"`
	PersonaId      string `json:"persona_id"`
	StartedAt      string `json:"started_at"`
	Status         string `json:"status"`
	StudyId        string `json:"study_id"`
}

type SimulationStartOut struct {
	CreditsUsed      string  `json:"credits_used"`
	DeliverSignals   bool    `json:"deliver_signals"`
	Error            string  `json:"error"`
	EstimatedCredits float64 `json:"estimated_credits"`
	Id               string  `json:"id"`
	InterviewId      string  `json:"interview_id"`
	ModelId          string  `json:"model_id"`
	ModelProvider    string  `json:"model_provider"`
	PersonaId        string  `json:"persona_id"`
	StartedAt        string  `json:"started_at"`
	Status           string  `json:"status"`
	StudyId          string  `json:"study_id"`
}

type SimulationStartRequest struct {
	DeliverSignals bool   `json:"deliver_signals"`
	ModelTier      string `json:"model_tier"`
	Persona        string `json:"persona"`
	PersonaId      string `json:"persona_id"`
}

type StudyCreate struct {
	Anonymous        bool   `json:"anonymous"`
	Benefits         string `json:"benefits"`
	Description      string `json:"description"`
	Institution      string `json:"institution"`
	Language         string `json:"language"`
	MaxResponses     string `json:"max_responses"`
	Methodology      string `json:"methodology"`
	ModelTier        string `json:"model_tier"`
	Name             string `json:"name"`
	Objectives       string `json:"objectives"`
	ProjectId        string `json:"project_id"`
	RedirectUrl      string `json:"redirect_url"`
	ResearchQuestion string `json:"research_question"`
	Risks            string `json:"risks"`
	SupportContact   string `json:"support_contact"`
	SurveyType       string `json:"survey_type"`
	TargetPopulation string `json:"target_population"`
	VideoEnabled     bool   `json:"video_enabled"`
	VoiceEnabled     bool   `json:"voice_enabled"`
}

type StudyListOut struct {
	ProjectId string          `json:"project_id"`
	Studies   json.RawMessage `json:"studies"`
}

type StudyOut struct {
	Anonymous                    bool   `json:"anonymous"`
	Benefits                     string `json:"benefits"`
	CharacteristicsEnabled       bool   `json:"characteristics_enabled"`
	CharacteristicsQuestionCount int    `json:"characteristics_question_count"`
	DashboardUrl                 string `json:"dashboard_url"`
	DateCreated                  string `json:"date_created"`
	Description                  string `json:"description"`
	HasWelcome                   bool   `json:"has_welcome"`
	Id                           string `json:"id"`
	Institution                  string `json:"institution"`
	InterviewMode                string `json:"interview_mode"`
	Language                     string `json:"language"`
	MaxResponses                 string `json:"max_responses"`
	Methodology                  string `json:"methodology"`
	ModelId                      string `json:"model_id"`
	ModelProvider                string `json:"model_provider"`
	ModelTier                    string `json:"model_tier"`
	Name                         string `json:"name"`
	Objectives                   string `json:"objectives"`
	ParticipationUrl             string `json:"participation_url"`
	ProjectId                    string `json:"project_id"`
	QuestionCount                int    `json:"question_count"`
	RedirectUrl                  string `json:"redirect_url"`
	RedirectUrlWarning           string `json:"redirect_url_warning"`
	ResearchQuestion             string `json:"research_question"`
	Risks                        string `json:"risks"`
	ScreeningEnabled             bool   `json:"screening_enabled"`
	ScreeningQuestionCount       int    `json:"screening_question_count"`
	ShortParticipationUrl        string `json:"short_participation_url"`
	ShortVideoParticipationUrl   string `json:"short_video_participation_url"`
	ShortVoiceParticipationUrl   string `json:"short_voice_participation_url"`
	SupportContact               string `json:"support_contact"`
	SurveyType                   string `json:"survey_type"`
	TargetPopulation             string `json:"target_population"`
	VideoEnabled                 bool   `json:"video_enabled"`
	VideoParticipationUrl        string `json:"video_participation_url"`
	VoiceEnabled                 bool   `json:"voice_enabled"`
	VoiceParticipationUrl        string `json:"voice_participation_url"`
}

type StudyStatsOut struct {
	CompletedInterviews  int     `json:"completed_interviews"`
	CompletionRate       float64 `json:"completion_rate"`
	IncompleteInterviews int     `json:"incomplete_interviews"`
	MaxResponses         string  `json:"max_responses"`
	QuotaFillRate        string  `json:"quota_fill_rate"`
	QuotaRemaining       string  `json:"quota_remaining"`
	SimulatedInterviews  int     `json:"simulated_interviews"`
	StudyId              string  `json:"study_id"`
	TotalInterviews      int     `json:"total_interviews"`
}

type StudySummary struct {
	DateCreated   string `json:"date_created"`
	Description   string `json:"description"`
	Id            string `json:"id"`
	InterviewMode string `json:"interview_mode"`
	Language      string `json:"language"`
	MaxResponses  string `json:"max_responses"`
	Name          string `json:"name"`
	SurveyType    string `json:"survey_type"`
}

type StudyUpdate struct {
	Anonymous        string `json:"anonymous"`
	Benefits         string `json:"benefits"`
	Description      string `json:"description"`
	Institution      string `json:"institution"`
	Language         string `json:"language"`
	MaxResponses     string `json:"max_responses"`
	Methodology      string `json:"methodology"`
	ModelTier        string `json:"model_tier"`
	Name             string `json:"name"`
	Objectives       string `json:"objectives"`
	RedirectUrl      string `json:"redirect_url"`
	ResearchQuestion string `json:"research_question"`
	Risks            string `json:"risks"`
	SupportContact   string `json:"support_contact"`
	SurveyType       string `json:"survey_type"`
	TargetPopulation string `json:"target_population"`
	VideoEnabled     string `json:"video_enabled"`
	VoiceEnabled     string `json:"voice_enabled"`
}

type SuccessResponse struct {
	Message string `json:"message"`
	Success bool   `json:"success"`
}

type TranscriptMessage struct {
	Content        string `json:"content"`
	Id             string `json:"id"`
	NodeId         string `json:"node_id"`
	QuestionNumber string `json:"question_number"`
	Timestamp      string `json:"timestamp"`
	Type           string `json:"type"`
}

type TranscriptOut struct {
	Completed             string          `json:"completed"`
	Decisions             json.RawMessage `json:"decisions"`
	ExternalParticipantId string          `json:"external_participant_id"`
	InterviewId           string          `json:"interview_id"`
	Messages              json.RawMessage `json:"messages"`
	ParticipantId         string          `json:"participant_id"`
	StudyId               string          `json:"study_id"`
	Variables             json.RawMessage `json:"variables"`
	WebSource             string          `json:"web_source"`
}

type TranscriptsBulkOut struct {
	Limit           int             `json:"limit"`
	Offset          int             `json:"offset"`
	StudyId         string          `json:"study_id"`
	TotalInterviews int             `json:"total_interviews"`
	Transcripts     json.RawMessage `json:"transcripts"`
}

type ValidationError struct {
	Ctx   json.RawMessage `json:"ctx"`
	Input string          `json:"input"`
	Loc   json.RawMessage `json:"loc"`
	Msg   string          `json:"msg"`
	Type  string          `json:"type"`
}

type ValidationOut struct {
	EthicsCheck json.RawMessage `json:"ethics_check"`
	Questions   json.RawMessage `json:"questions"`
	StudyId     string          `json:"study_id"`
}

type WebhookCreate struct {
	Enabled bool            `json:"enabled"`
	Events  json.RawMessage `json:"events"`
	Label   string          `json:"label"`
	Url     string          `json:"url"`
}

type WebhookCreatedOut struct {
	SigningSecret string          `json:"signing_secret"`
	Webhook       json.RawMessage `json:"webhook"`
}

type WebhookDeleteOut struct {
	Deleted   bool   `json:"deleted"`
	WebhookId string `json:"webhook_id"`
}

type WebhookDeliveryListOut struct {
	Deliveries json.RawMessage `json:"deliveries"`
	Limit      int             `json:"limit"`
	Offset     int             `json:"offset"`
	Total      int             `json:"total"`
	WebhookId  string          `json:"webhook_id"`
}

type WebhookDeliveryOut struct {
	CreatedAt             string `json:"created_at"`
	ErrorMessage          string `json:"error_message"`
	EventType             string `json:"event_type"`
	ExternalParticipantId string `json:"external_participant_id"`
	Id                    string `json:"id"`
	MsgId                 string `json:"msg_id"`
	StatusCode            string `json:"status_code"`
	Success               bool   `json:"success"`
}

type WebhookEventTypeListOut struct {
	Envelope         string          `json:"envelope"`
	EventTypes       json.RawMessage `json:"event_types"`
	SignatureHeaders json.RawMessage `json:"signature_headers"`
}

type WebhookEventTypeOut struct {
	DataFields  json.RawMessage `json:"data_fields"`
	Description string          `json:"description"`
	EventType   string          `json:"event_type"`
}

type WebhookListOut struct {
	EventTypes json.RawMessage `json:"event_types"`
	Total      int             `json:"total"`
	Webhooks   json.RawMessage `json:"webhooks"`
}

type WebhookOut struct {
	CreatedAt string          `json:"created_at"`
	Enabled   bool            `json:"enabled"`
	Events    json.RawMessage `json:"events"`
	Id        string          `json:"id"`
	Label     string          `json:"label"`
	UpdatedAt string          `json:"updated_at"`
	Url       string          `json:"url"`
}

type WebhookSecretOut struct {
	SigningSecret string          `json:"signing_secret"`
	Webhook       json.RawMessage `json:"webhook"`
}

type WebhookUpdate struct {
	Enabled string `json:"enabled"`
	Events  string `json:"events"`
	Label   string `json:"label"`
	Url     string `json:"url"`
}

type WelcomeOut struct {
	Configured bool   `json:"configured"`
	Consent    bool   `json:"consent"`
	Message    string `json:"message"`
}

type WelcomeSet struct {
	Consent bool   `json:"consent"`
	Message string `json:"message"`
}

type WelcomeTranslationListOut struct {
	Translations json.RawMessage `json:"translations"`
}

type WelcomeTranslationOut struct {
	Id              string `json:"id"`
	SourceLanguage  string `json:"source_language"`
	TargetLanguage  string `json:"target_language"`
	Timestamp       string `json:"timestamp"`
	TranslationText string `json:"translation_text"`
}

type WelcomeTranslationSet struct {
	SourceLanguage  string `json:"source_language"`
	TargetLanguage  string `json:"target_language"`
	TranslationText string `json:"translation_text"`
}
