// Copyright 2026 francis and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package mcp — code-orchestration thin surface.
//
// Three tools cover the entire API: <api>_search to discover endpoints,
// <api>_get to inspect one GET endpoint, and <api>_execute to invoke one.
// This collapses a large API (50+ endpoints)
// to ~1K tokens of tool definitions while preserving full coverage — the
// agent writes the composition logic in its own sandbox.
//
// Pattern source: Anthropic 2026-04-22 "Building agents that reach
// production systems with MCP" — Cloudflare's MCP server covers ~2,500
// endpoints in roughly 1K tokens via the same search, get, and execute shape.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	neturl "net/url"
	"sort"
	"strings"

	"github.com/deutero-ai/deutero-cli/internal/cli"
	"github.com/deutero-ai/deutero-cli/internal/mcp/bound"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterCodeOrchestrationTools registers the agent-facing tools that cover
// the whole API surface. Called from RegisterTools in place of the per-endpoint
// registrations when MCP.Orchestration is "code".
func RegisterCodeOrchestrationTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("deutero_search",
			mcplib.WithDescription("Search the deutero API for endpoints matching a natural-language query. Returns a ranked list of {endpoint_id, method, path, summary} entries. Call this first to find the endpoint to execute."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Natural-language description of what you want to do.")),
			mcplib.WithNumber("limit", mcplib.Description("Max endpoints to return (default 10, max 100).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(false),
		),
		handleCodeOrchSearch,
	)

	s.AddTool(
		mcplib.NewTool("deutero_get",
			mcplib.WithDescription("Get metadata for one GET endpoint by its endpoint_id (from deutero_search). This registry-only lookup never calls the API."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("GET endpoint identifier returned by deutero_search (e.g., \"users.list\").")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(false),
		),
		handleCodeOrchGet,
	)

	s.AddTool(
		mcplib.NewTool("deutero_execute",
			mcplib.WithDescription("Execute one deutero API endpoint by its endpoint_id (from deutero_search). Params are passed as a JSON object; path placeholders and query strings are resolved automatically."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("Endpoint identifier returned by deutero_search (e.g., \"users.list\").")),
			mcplib.WithObject("params", mcplib.Description("Parameters for the endpoint. Path placeholders match by name; remaining entries become query string on GET/DELETE or JSON body on POST/PUT/PATCH.")),
		),
		handleCodeOrchExecute,
	)
}

// codeOrchEndpoint captures the small slice of endpoint metadata the
// registry tools need at runtime. `keywords` is a precomputed
// lowercase stream of description + path tokens used for naive ranking;
// anything more sophisticated belongs on the agent side.
type codeOrchEndpoint struct {
	ID         string
	Method     string
	Path       string
	Tier       string
	Summary    string
	Positional []string
	// TemplateParams carries public-to-wire bindings for promoted global path
	// placeholders. These resolve through Config.TemplateVars just like the
	// per-endpoint MCP tool inputs do.
	TemplateParams []codeOrchParamBinding
	// QueryParams carries public-to-wire bindings for spec-declared in:query
	// parameters. Write methods (POST/PUT/PATCH) route these to the query
	// string instead of dumping them into the JSON body. Derived from the
	// same mcpParamBindings location data the per-endpoint tools use.
	QueryParams []codeOrchParamBinding
	// Keep declared headers out of query/body routing so execution sends them
	// through the request-header map.
	HeaderParams []codeOrchParamBinding
	// HeaderOverrides carries per-endpoint request headers (e.g. an
	// Accept override for binary-only response endpoints). Without
	// threading these through, the code-orchestration execute path
	// sends the client's default Accept and binary endpoints 406.
	HeaderOverrides map[string]string
	// BodyIsArray marks endpoints whose request body schema root is a
	// bare top-level JSON array. The execute path then sends a top-level
	// array (the agent supplies it as params["body"]) instead of the
	// params object; a strict-mapping API rejects an object at the body
	// root with HTTP 422 "Invalid json".
	BodyIsArray bool
	Mutating    bool
	keywords    []string
}

type codeOrchParamBinding struct {
	PublicName string
	WireName   string
	Default    string
}

// codeOrchEndpoints is the generator-populated registry covering every
// endpoint declared in the spec. Kept flat on purpose — the agent queries
// via <api>_search, so hierarchy shows up as dotted IDs, not nested maps.
var codeOrchEndpoints = []codeOrchEndpoint{
	{
		ID:             "credits.get-balance",
		Method:         "GET",
		Path:           "/api/v1/credits/balance",
		Summary:        "Get credit balance",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("credits", "get-balance", "Get credit balance", "/api/v1/credits/balance"),
	},
	{
		ID:             "embed.create",
		Method:         "POST",
		Path:           "/api/v1/embed/keys",
		Summary:        "Create a publishable embed key for the caller's organization, optionally pinned to one study.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("embed", "create", "Create a publishable embed key for the caller's organization, optionally pinned to one study.", "/api/v1/embed/keys"),
	},
	{
		ID:             "embed.list-keys",
		Method:         "GET",
		Path:           "/api/v1/embed/keys",
		Summary:        "Every embed key owned by the caller's organization (secrets omitted).",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("embed", "list-keys", "Every embed key owned by the caller's organization (secrets omitted).", "/api/v1/embed/keys"),
	},
	{
		ID:             "embed.update",
		Method:         "PATCH",
		Path:           "/api/v1/embed/keys/{key_id}",
		Summary:        "Change allowed origins, revoke/reactivate (``status``), or adjust the metadata size limit.",
		Positional:     []string{"key_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("embed", "update", "Change allowed origins, revoke/reactivate (``status``), or adjust the metadata size limit.", "/api/v1/embed/keys/{key_id}"),
	},
	{
		ID:             "graph.describe-nodes",
		Method:         "GET",
		Path:           "/api/v1/graph/node-types",
		Summary:        "The configuration schema for every step type an interview flow can contain",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("graph", "describe-nodes", "The configuration schema for every step type an interview flow can contain", "/api/v1/graph/node-types"),
	},
	{
		ID:             "health.health",
		Method:         "GET",
		Path:           "/health",
		Summary:        "Liveness check",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("health", "health", "Liveness check", "/health"),
	},
	{
		ID:             "interviews.get",
		Method:         "GET",
		Path:           "/api/v1/interviews/{interview_id}",
		Summary:        "One interview with its screening answers, participant characteristics, embed-widget metadata (with per-key provenance)",
		Positional:     []string{"interview_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("interviews", "get", "One interview with its screening answers, participant characteristics, embed-widget metadata (with per-key provenance)", "/api/v1/interviews/{interview_id}"),
	},
	{
		ID:             "interviews.fetches-and-signals.get-interview",
		Method:         "GET",
		Path:           "/api/v1/interviews/{interview_id}/fetches-and-signals",
		Summary:        "What an Interview Flow's side steps did outside the conversation: every 'Bring in data' (context_fetch)",
		Positional:     []string{"interview_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("interviews", "get-interview", "What an Interview Flow's side steps did outside the conversation: every 'Bring in data' (context_fetch)", "/api/v1/interviews/{interview_id}/fetches-and-signals"),
	},
	{
		ID:             "interviews.transcript.get",
		Method:         "GET",
		Path:           "/api/v1/interviews/{interview_id}/transcript",
		Summary:        "All messages in chronological order.",
		Positional:     []string{"interview_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("interviews", "get", "All messages in chronological order.", "/api/v1/interviews/{interview_id}/transcript"),
	},
	{
		ID:             "projects.create",
		Method:         "POST",
		Path:           "/api/v1/projects",
		Summary:        "Create a new project owned by the caller's organization.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("projects", "create", "Create a new project owned by the caller's organization.", "/api/v1/projects"),
	},
	{
		ID:             "projects.get",
		Method:         "GET",
		Path:           "/api/v1/projects/{project_id}",
		Summary:        "Get a project",
		Positional:     []string{"project_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("projects", "get", "Get a project", "/api/v1/projects/{project_id}"),
	},
	{
		ID:             "projects.list",
		Method:         "GET",
		Path:           "/api/v1/projects",
		Summary:        "List every project in the caller's organization.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("projects", "list", "List every project in the caller's organization.", "/api/v1/projects"),
	},
	{
		ID:             "projects.update",
		Method:         "PATCH",
		Path:           "/api/v1/projects/{project_id}",
		Summary:        "Update a project's name and/or description. Omitted fields are untouched.",
		Positional:     []string{"project_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("projects", "update", "Update a project's name and/or description. Omitted fields are untouched.", "/api/v1/projects/{project_id}"),
	},
	{
		ID:             "projects.studies.list",
		Method:         "GET",
		Path:           "/api/v1/projects/{project_id}/studies",
		Summary:        "List studies in a project",
		Positional:     []string{"project_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("projects", "list", "List studies in a project", "/api/v1/projects/{project_id}/studies"),
	},
	{
		ID:             "simulations.delete",
		Method:         "DELETE",
		Path:           "/api/v1/simulations/{simulation_id}",
		Summary:        "Removes the run's bookkeeping row.",
		Positional:     []string{"simulation_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("simulations", "delete", "Removes the run's bookkeeping row.", "/api/v1/simulations/{simulation_id}"),
	},
	{
		ID:             "simulations.get",
		Method:         "GET",
		Path:           "/api/v1/simulations/{simulation_id}",
		Summary:        "One run's current state.",
		Positional:     []string{"simulation_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("simulations", "get", "One run's current state.", "/api/v1/simulations/{simulation_id}"),
	},
	{
		ID:             "studies.create",
		Method:         "POST",
		Path:           "/api/v1/studies",
		Summary:        "Create a new study inside a project.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "create", "Create a new study inside a project.", "/api/v1/studies"),
	},
	{
		ID:             "studies.get-study",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}",
		Summary:        "Full study configuration, including per-lifecycle-stage status (welcome configured",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "get-study", "Full study configuration, including per-lifecycle-stage status (welcome configured", "/api/v1/studies/{study_id}"),
	},
	{
		ID:             "studies.update",
		Method:         "PATCH",
		Path:           "/api/v1/studies/{study_id}",
		Summary:        "Partial update of study properties. Only fields present in the request body are changed.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "update", "Partial update of study properties. Only fields present in the request body are changed.", "/api/v1/studies/{study_id}"),
	},
	{
		ID:             "studies.analysis.get-latest-clustering",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/analysis/clustering/latest",
		Summary:        "Returns the study's most recent saved clustering run, ready to chart: per-cluster point coordinates and centroids.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "get-latest-clustering", "Returns the study's most recent saved clustering run, ready to chart: per-cluster point coordinates and centroids.", "/api/v1/studies/{study_id}/analysis/clustering/latest"),
	},
	{
		ID:             "studies.analysis.get-optimal-clusters",
		Method:         "POST",
		Path:           "/api/v1/studies/{study_id}/analysis/optimal-clusters",
		Summary:        "Suggests how many clusters to use for a question.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "get-optimal-clusters", "Suggests how many clusters to use for a question.", "/api/v1/studies/{study_id}/analysis/optimal-clusters"),
	},
	{
		ID:             "studies.analysis.get-options-responses",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/analysis/responses/options",
		Summary:        "Response count per option.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "question_id", WireName: "question_id"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "get-options-responses", "Response count per option.", "/api/v1/studies/{study_id}/analysis/responses/options"),
	},
	{
		ID:             "studies.analysis.get-scale-responses",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/analysis/responses/scale",
		Summary:        "Response count per scale value. Follow-up turns are excluded; out-of-range and non-numeric replies are skipped.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "question_id", WireName: "question_id"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "get-scale-responses", "Response count per scale value. Follow-up turns are excluded; out-of-range and non-numeric replies are skipped.", "/api/v1/studies/{study_id}/analysis/responses/scale"),
	},
	{
		ID:             "studies.analysis.list-analyzable-questions",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/analysis/questions",
		Summary:        "Questions of the study that fit the requested analysis ``category``: * ``text`` — free-text questions (clusterable",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "category", WireName: "category"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "list-analyzable-questions", "Questions of the study that fit the requested analysis ``category``: * ``text`` — free-text questions (clusterable", "/api/v1/studies/{study_id}/analysis/questions"),
	},
	{
		ID:             "studies.analysis.run-clustering",
		Method:         "POST",
		Path:           "/api/v1/studies/{study_id}/analysis/cluster",
		Summary:        "Group participants' free-text answers to one question into themes.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "run-clustering", "Group participants' free-text answers to one question into themes.", "/api/v1/studies/{study_id}/analysis/cluster"),
	},
	{
		ID:             "studies.characteristics.create",
		Method:         "POST",
		Path:           "/api/v1/studies/{study_id}/characteristics/questions",
		Summary:        "Add a characteristic question",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "create", "Add a characteristic question", "/api/v1/studies/{study_id}/characteristics/questions"),
	},
	{
		ID:             "studies.characteristics.delete",
		Method:         "DELETE",
		Path:           "/api/v1/studies/{study_id}/characteristics/questions/{question_id}",
		Summary:        "Delete a characteristic question",
		Positional:     []string{"question_id", "study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "delete", "Delete a characteristic question", "/api/v1/studies/{study_id}/characteristics/questions/{question_id}"),
	},
	{
		ID:             "studies.characteristics.get",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/characteristics",
		Summary:        "Settings plus the ordered characteristic question list.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "get", "Settings plus the ordered characteristic question list.", "/api/v1/studies/{study_id}/characteristics"),
	},
	{
		ID:             "studies.characteristics.reorder-questions",
		Method:         "PUT",
		Path:           "/api/v1/studies/{study_id}/characteristics/questions/order",
		Summary:        "Supply every characteristic question ID in the desired order.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "reorder-questions", "Supply every characteristic question ID in the desired order.", "/api/v1/studies/{study_id}/characteristics/questions/order"),
	},
	{
		ID:             "studies.characteristics.set-settings",
		Method:         "PUT",
		Path:           "/api/v1/studies/{study_id}/characteristics/settings",
		Summary:        "Enable/disable characteristic collection. Disabling preserves the question list.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "set-settings", "Enable/disable characteristic collection. Disabling preserves the question list.", "/api/v1/studies/{study_id}/characteristics/settings"),
	},
	{
		ID:             "studies.characteristics.update",
		Method:         "PATCH",
		Path:           "/api/v1/studies/{study_id}/characteristics/questions/{question_id}",
		Summary:        "Update a characteristic question",
		Positional:     []string{"question_id", "study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "update", "Update a characteristic question", "/api/v1/studies/{study_id}/characteristics/questions/{question_id}"),
	},
	{
		ID:             "studies.embed.get-snippet",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/embed/snippet",
		Summary:        "Generate the HTML install snippet for embedding this study's interview widget.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "publishable_key", WireName: "publishable_key"}, {PublicName: "mode", WireName: "mode"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "get-snippet", "Generate the HTML install snippet for embedding this study's interview widget.", "/api/v1/studies/{study_id}/embed/snippet"),
	},
	{
		ID:             "studies.graph.activate",
		Method:         "POST",
		Path:           "/api/v1/studies/{study_id}/graph/activate",
		Summary:        "Switch the study to `graph` mode: interviews follow the stored flow instead of the linear question list.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "activate", "Switch the study to `graph` mode: interviews follow the stored flow instead of the linear question list.", "/api/v1/studies/{study_id}/graph/activate"),
	},
	{
		ID:             "studies.graph.check",
		Method:         "POST",
		Path:           "/api/v1/studies/{study_id}/graph/check",
		Summary:        "Validate a flow and report every problem, changing nothing.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "check", "Validate a flow and report every problem, changing nothing.", "/api/v1/studies/{study_id}/graph/check"),
	},
	{
		ID:             "studies.graph.deactivate",
		Method:         "POST",
		Path:           "/api/v1/studies/{study_id}/graph/deactivate",
		Summary:        "Switch the study back to `linear` mode. The stored flow is kept, just not used.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "deactivate", "Switch the study back to `linear` mode. The stored flow is kept, just not used.", "/api/v1/studies/{study_id}/graph/deactivate"),
	},
	{
		ID:             "studies.graph.get",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/graph",
		Summary:        "The study's interview flow, in the same shape `set_graph` accepts — so you can read it, change part of it",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "get", "The study's interview flow, in the same shape `set_graph` accepts — so you can read it, change part of it", "/api/v1/studies/{study_id}/graph"),
	},
	{
		ID:             "studies.graph.get-flow-signals",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/graph/signals",
		Summary:        "The delivery config behind every 'Send a signal' (`webhook`) step in the saved flow",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "get-flow-signals", "The delivery config behind every 'Send a signal' (`webhook`) step in the saved flow", "/api/v1/studies/{study_id}/graph/signals"),
	},
	{
		ID:             "studies.graph.import-questions-to",
		Method:         "POST",
		Path:           "/api/v1/studies/{study_id}/graph/import-questions",
		Summary:        "Build a straight-line flow from the study's existing linear questions — start → each question in order → end — and save",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "import-questions-to", "Build a straight-line flow from the study's existing linear questions — start → each question in order → end — and save", "/api/v1/studies/{study_id}/graph/import-questions"),
	},
	{
		ID:             "studies.graph.patch",
		Method:         "PATCH",
		Path:           "/api/v1/studies/{study_id}/graph",
		Summary:        "Apply targeted edits to the stored flow instead of rewriting it — safer than read-modify-write on a large flow",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "patch", "Apply targeted edits to the stored flow instead of rewriting it — safer than read-modify-write on a large flow", "/api/v1/studies/{study_id}/graph"),
	},
	{
		ID:             "studies.graph.set",
		Method:         "PUT",
		Path:           "/api/v1/studies/{study_id}/graph",
		Summary:        "Write a complete interview flow, replacing whatever is stored.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "set", "Write a complete interview flow, replacing whatever is stored.", "/api/v1/studies/{study_id}/graph"),
	},
	{
		ID:             "studies.interviews.find-by-external-id",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/interviews/by-external-id",
		Summary:        "Every interview in this study that arrived carrying ``external_participant_id`` — your own id for the person",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "external_participant_id", WireName: "external_participant_id"}, {PublicName: "include_simulated", WireName: "include_simulated"}, {PublicName: "limit", WireName: "limit"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "find-by-external-id", "Every interview in this study that arrived carrying ``external_participant_id`` — your own id for the person", "/api/v1/studies/{study_id}/interviews/by-external-id"),
	},
	{
		ID:             "studies.interviews.list",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/interviews",
		Summary:        "Interviews for a study, newest first. Filter by completion status, simulation flag, and start-time range.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "completed", WireName: "completed"}, {PublicName: "simulated", WireName: "simulated"}, {PublicName: "external_participant_id", WireName: "external_participant_id"}, {PublicName: "started_after", WireName: "started_after"}, {PublicName: "started_before", WireName: "started_before"}, {PublicName: "limit", WireName: "limit"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "list", "Interviews for a study, newest first. Filter by completion status, simulation flag, and start-time range.", "/api/v1/studies/{study_id}/interviews"),
	},
	{
		ID:             "studies.personas.create",
		Method:         "POST",
		Path:           "/api/v1/studies/{study_id}/personas",
		Summary:        "Write a persona by hand.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "create", "Write a persona by hand.", "/api/v1/studies/{study_id}/personas"),
	},
	{
		ID:             "studies.personas.delete",
		Method:         "DELETE",
		Path:           "/api/v1/studies/{study_id}/personas/{persona_id}",
		Summary:        "Interviews already simulated with this persona are kept.",
		Positional:     []string{"persona_id", "study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "delete", "Interviews already simulated with this persona are kept.", "/api/v1/studies/{study_id}/personas/{persona_id}"),
	},
	{
		ID:             "studies.personas.generate",
		Method:         "POST",
		Path:           "/api/v1/studies/{study_id}/personas/generate",
		Summary:        "Draft personas from the study's own context — its type, description, research question",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "generate", "Draft personas from the study's own context — its type, description, research question", "/api/v1/studies/{study_id}/personas/generate"),
	},
	{
		ID:             "studies.personas.list",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/personas",
		Summary:        "Every persona defined for the study, newest first.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "list", "Every persona defined for the study, newest first.", "/api/v1/studies/{study_id}/personas"),
	},
	{
		ID:             "studies.personas.update",
		Method:         "PATCH",
		Path:           "/api/v1/studies/{study_id}/personas/{persona_id}",
		Summary:        "Replace a persona's description. Simulations already run keep the text they ran against — this only affects future runs.",
		Positional:     []string{"persona_id", "study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "update", "Replace a persona's description. Simulations already run keep the text they ran against — this only affects future runs.", "/api/v1/studies/{study_id}/personas/{persona_id}"),
	},
	{
		ID:             "studies.questions.create",
		Method:         "POST",
		Path:           "/api/v1/studies/{study_id}/questions",
		Summary:        "Create a question and append it to the end of the study's question list.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "create", "Create a question and append it to the end of the study's question list.", "/api/v1/studies/{study_id}/questions"),
	},
	{
		ID:             "studies.questions.delete",
		Method:         "DELETE",
		Path:           "/api/v1/studies/{study_id}/questions/{question_id}",
		Summary:        "Removes the question, its attached images, and its list entry; remaining questions are renumbered.",
		Positional:     []string{"question_id", "study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "delete", "Removes the question, its attached images, and its list entry; remaining questions are renumbered.", "/api/v1/studies/{study_id}/questions/{question_id}"),
	},
	{
		ID:             "studies.questions.list",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/questions",
		Summary:        "The study's main questions, resolved and in interview order.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "list", "The study's main questions, resolved and in interview order.", "/api/v1/studies/{study_id}/questions"),
	},
	{
		ID:             "studies.questions.reorder",
		Method:         "PUT",
		Path:           "/api/v1/studies/{study_id}/questions/order",
		Summary:        "Supply every question ID in the desired interview order.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "reorder", "Supply every question ID in the desired interview order.", "/api/v1/studies/{study_id}/questions/order"),
	},
	{
		ID:             "studies.questions.update",
		Method:         "PATCH",
		Path:           "/api/v1/studies/{study_id}/questions/{question_id}",
		Summary:        "Partial update. Pass an empty list to clear ``options``/``slots``/``groups``.",
		Positional:     []string{"question_id", "study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "update", "Partial update. Pass an empty list to clear ``options``/``slots``/``groups``.", "/api/v1/studies/{study_id}/questions/{question_id}"),
	},
	{
		ID:             "studies.questions.validate",
		Method:         "POST",
		Path:           "/api/v1/studies/{study_id}/questions/validate",
		Summary:        "Review the study's questions before it goes live, the same check the dashboard's **Validate** button runs.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "validate", "Review the study's questions before it goes live, the same check the dashboard's **Validate** button runs.", "/api/v1/studies/{study_id}/questions/validate"),
	},
	{
		ID:             "studies.recruitment.get",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/recruitment",
		Summary:        "Participation links, quota status, and pre-interview gate flags.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "get", "Participation links, quota status, and pre-interview gate flags.", "/api/v1/studies/{study_id}/recruitment"),
	},
	{
		ID:             "studies.recruitment.update",
		Method:         "PUT",
		Path:           "/api/v1/studies/{study_id}/recruitment",
		Summary:        "Set a custom short-link slug, the response quota, and/or the post-completion redirect URL.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "update", "Set a custom short-link slug, the response quota, and/or the post-completion redirect URL.", "/api/v1/studies/{study_id}/recruitment"),
	},
	{
		ID:             "studies.screening.create",
		Method:         "POST",
		Path:           "/api/v1/studies/{study_id}/screening/questions",
		Summary:        "Appends a multiple-choice qualifying question. ``acceptable_options`` must be a subset of ``options``.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "create", "Appends a multiple-choice qualifying question. ``acceptable_options`` must be a subset of ``options``.", "/api/v1/studies/{study_id}/screening/questions"),
	},
	{
		ID:             "studies.screening.delete",
		Method:         "DELETE",
		Path:           "/api/v1/studies/{study_id}/screening/questions/{question_id}",
		Summary:        "Removes the question and renumbers the remaining list. Any recorded participant answers to it are deleted with it.",
		Positional:     []string{"question_id", "study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "delete", "Removes the question and renumbers the remaining list. Any recorded participant answers to it are deleted with it.", "/api/v1/studies/{study_id}/screening/questions/{question_id}"),
	},
	{
		ID:             "studies.screening.get",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/screening",
		Summary:        "Settings plus the ordered screening question list.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "get", "Settings plus the ordered screening question list.", "/api/v1/studies/{study_id}/screening"),
	},
	{
		ID:             "studies.screening.reorder-questions",
		Method:         "PUT",
		Path:           "/api/v1/studies/{study_id}/screening/questions/order",
		Summary:        "Supply every screening question ID in the desired order.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "reorder-questions", "Supply every screening question ID in the desired order.", "/api/v1/studies/{study_id}/screening/questions/order"),
	},
	{
		ID:             "studies.screening.set-settings",
		Method:         "PUT",
		Path:           "/api/v1/studies/{study_id}/screening/settings",
		Summary:        "Enable/disable screening and set the disqualification message and redirect URL.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "set-settings", "Enable/disable screening and set the disqualification message and redirect URL.", "/api/v1/studies/{study_id}/screening/settings"),
	},
	{
		ID:             "studies.screening.update",
		Method:         "PATCH",
		Path:           "/api/v1/studies/{study_id}/screening/questions/{question_id}",
		Summary:        "Update a screening question",
		Positional:     []string{"question_id", "study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "update", "Update a screening question", "/api/v1/studies/{study_id}/screening/questions/{question_id}"),
	},
	{
		ID:             "studies.search.transcripts",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/search",
		Summary:        "Search participant answers in a study.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "q", WireName: "q"}, {PublicName: "mode", WireName: "mode"}, {PublicName: "question_id", WireName: "question_id"}, {PublicName: "completed_only", WireName: "completed_only"}, {PublicName: "include_simulated", WireName: "include_simulated"}, {PublicName: "external_participant_id", WireName: "external_participant_id"}, {PublicName: "strict", WireName: "strict"}, {PublicName: "limit", WireName: "limit"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "transcripts", "Search participant answers in a study.", "/api/v1/studies/{study_id}/search"),
	},
	{
		ID:             "studies.simulations.list",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/simulations",
		Summary:        "Every simulation run for the study, newest first, with the interview each produced and what it cost.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "status", WireName: "status"}, {PublicName: "limit", WireName: "limit"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "list", "Every simulation run for the study, newest first, with the interview each produced and what it cost.", "/api/v1/studies/{study_id}/simulations"),
	},
	{
		ID:             "studies.simulations.run",
		Method:         "POST",
		Path:           "/api/v1/studies/{study_id}/simulations",
		Summary:        "Start one simulated interview and return immediately — the run continues in the background",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "run", "Start one simulated interview and return immediately — the run continues in the background", "/api/v1/studies/{study_id}/simulations"),
	},
	{
		ID:             "studies.stats.get-study",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/stats",
		Summary:        "Counts of started/completed/incomplete interviews, completion rate, and quota fill relative to ``max_responses``.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "get-study", "Counts of started/completed/incomplete interviews, completion rate, and quota fill relative to ``max_responses``.", "/api/v1/studies/{study_id}/stats"),
	},
	{
		ID:             "studies.transcripts.bulk",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/transcripts",
		Summary:        "Full transcripts for a study's interviews, newest interview first, paginated by interview.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "completed", WireName: "completed"}, {PublicName: "include_simulated", WireName: "include_simulated"}, {PublicName: "external_participant_id", WireName: "external_participant_id"}, {PublicName: "limit", WireName: "limit"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "bulk", "Full transcripts for a study's interviews, newest interview first, paginated by interview.", "/api/v1/studies/{study_id}/transcripts"),
	},
	{
		ID:             "studies.welcome.delete",
		Method:         "DELETE",
		Path:           "/api/v1/studies/{study_id}/welcome/translations/{translation_id}",
		Summary:        "Delete a translation",
		Positional:     []string{"translation_id", "study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "delete", "Delete a translation", "/api/v1/studies/{study_id}/welcome/translations/{translation_id}"),
	},
	{
		ID:             "studies.welcome.get",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/welcome",
		Summary:        "Get the welcome message",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "get", "Get the welcome message", "/api/v1/studies/{study_id}/welcome"),
	},
	{
		ID:             "studies.welcome.list-translations",
		Method:         "GET",
		Path:           "/api/v1/studies/{study_id}/welcome/translations",
		Summary:        "List welcome-message translations",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "list-translations", "List welcome-message translations", "/api/v1/studies/{study_id}/welcome/translations"),
	},
	{
		ID:             "studies.welcome.set",
		Method:         "PUT",
		Path:           "/api/v1/studies/{study_id}/welcome",
		Summary:        "Create or replace the study's welcome/consent message.",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "set", "Create or replace the study's welcome/consent message.", "/api/v1/studies/{study_id}/welcome"),
	},
	{
		ID:             "studies.welcome.upsert-translation",
		Method:         "PUT",
		Path:           "/api/v1/studies/{study_id}/welcome/translations",
		Summary:        "Upserts the translation for ``target_language`` (one translation per target language).",
		Positional:     []string{"study_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("studies", "upsert-translation", "Upserts the translation for ``target_language`` (one translation per target language).", "/api/v1/studies/{study_id}/welcome/translations"),
	},
	{
		ID:             "webhooks.create",
		Method:         "POST",
		Path:           "/api/v1/webhooks",
		Summary:        "Subscribe a URL of yours to organization events.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("webhooks", "create", "Subscribe a URL of yours to organization events.", "/api/v1/webhooks"),
	},
	{
		ID:             "webhooks.delete",
		Method:         "DELETE",
		Path:           "/api/v1/webhooks/{webhook_id}",
		Summary:        "Permanently removes the endpoint and its delivery log.",
		Positional:     []string{"webhook_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("webhooks", "delete", "Permanently removes the endpoint and its delivery log.", "/api/v1/webhooks/{webhook_id}"),
	},
	{
		ID:             "webhooks.list",
		Method:         "GET",
		Path:           "/api/v1/webhooks",
		Summary:        "Every webhook endpoint in your organization, newest first.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("webhooks", "list", "Every webhook endpoint in your organization, newest first.", "/api/v1/webhooks"),
	},
	{
		ID:             "webhooks.list-event-types",
		Method:         "GET",
		Path:           "/api/v1/webhooks/event-types",
		Summary:        "Every event an endpoint can subscribe to, what makes it fire",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("webhooks", "list-event-types", "Every event an endpoint can subscribe to, what makes it fire", "/api/v1/webhooks/event-types"),
	},
	{
		ID:             "webhooks.update",
		Method:         "PATCH",
		Path:           "/api/v1/webhooks/{webhook_id}",
		Summary:        "Partial update: only the fields you send change.",
		Positional:     []string{"webhook_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("webhooks", "update", "Partial update: only the fields you send change.", "/api/v1/webhooks/{webhook_id}"),
	},
	{
		ID:             "webhooks.deliveries.list-webhook",
		Method:         "GET",
		Path:           "/api/v1/webhooks/{webhook_id}/deliveries",
		Summary:        "The delivery log for one endpoint, newest first: what was sent, who it was about, the status your server returned",
		Positional:     []string{"webhook_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "event_type", WireName: "event_type"}, {PublicName: "success", WireName: "success"}, {PublicName: "external_participant_id", WireName: "external_participant_id"}, {PublicName: "limit", WireName: "limit"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("webhooks", "list-webhook", "The delivery log for one endpoint, newest first: what was sent, who it was about, the status your server returned", "/api/v1/webhooks/{webhook_id}/deliveries"),
	},
	{
		ID:             "webhooks.rotate-secret.rotate-webhook-secret",
		Method:         "POST",
		Path:           "/api/v1/webhooks/{webhook_id}/rotate-secret",
		Summary:        "Mint a new signing secret for this endpoint and return it — the only other time a secret is shown.",
		Positional:     []string{"webhook_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("webhooks", "rotate-webhook-secret", "Mint a new signing secret for this endpoint and return it — the only other time a secret is shown.", "/api/v1/webhooks/{webhook_id}/rotate-secret"),
	},
}

// codeOrchStopwords filters two-letter and short common-word substrings
// that pollute ranking via the substring-contains rule. Without them, a
// search for "list links" matches every endpoint whose description
// contains "is enrolled" because "is" is two chars and the matcher
// accepts kw.contains(t) || t.contains(kw).
var codeOrchStopwords = map[string]bool{
	"a": true, "an": true, "and": true, "are": true, "as": true,
	"at": true, "be": true, "by": true, "for": true, "from": true,
	"has": true, "in": true, "is": true, "it": true, "its": true,
	"of": true, "on": true, "or": true, "that": true, "the": true,
	"this": true, "to": true, "was": true, "will": true, "with": true,
	"your": true, "you": true, "any": true, "all": true,
}

// codeOrchKeywords produces the lowercase token stream used for search
// ranking. Defined at package level so the registry initializer can call it
// inline above without pulling in a separate precompute step.
func codeOrchKeywords(resource, endpoint, summary, path string) []string {
	raw := strings.ToLower(resource + " " + endpoint + " " + summary + " " + path)
	raw = strings.Map(func(r rune) rune {
		switch r {
		case '_', '-', '/', '{', '}', '.', ',', ':', ';':
			return ' '
		}
		return r
	}, raw)
	out := make([]string, 0, 16)
	seen := map[string]bool{}
	for _, tok := range strings.Fields(raw) {
		if len(tok) < 3 || codeOrchStopwords[tok] || seen[tok] {
			continue
		}
		seen[tok] = true
		out = append(out, tok)
	}
	return out
}

func codeOrchEndpointMetadata(ep *codeOrchEndpoint) map[string]any {
	out := map[string]any{
		"endpoint_id": ep.ID,
		"method":      ep.Method,
		"path":        ep.Path,
		"summary":     ep.Summary,
	}
	return out
}

func findCodeOrchEndpoint(id string) *codeOrchEndpoint {
	for i := range codeOrchEndpoints {
		if codeOrchEndpoints[i].ID == id {
			return &codeOrchEndpoints[i]
		}
	}
	return nil
}

const (
	codeOrchSearchDefaultLimit = 10
	codeOrchSearchMaxLimit     = 100
)

func codeOrchSearchLimit(args map[string]any) int {
	if v, ok := args["limit"].(float64); ok && v > 0 {
		if v > float64(codeOrchSearchMaxLimit) {
			return codeOrchSearchMaxLimit
		}
		return int(v)
	}
	return codeOrchSearchDefaultLimit
}

func handleCodeOrchSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || strings.TrimSpace(query) == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}
	limit := codeOrchSearchLimit(args)

	terms := codeOrchKeywords("", "", query, "")
	type scored struct {
		ep    *codeOrchEndpoint
		score int
	}
	results := make([]scored, 0, len(codeOrchEndpoints))
	for i := range codeOrchEndpoints {
		ep := &codeOrchEndpoints[i]
		score := 0
		for _, t := range terms {
			for _, kw := range ep.keywords {
				if kw == t {
					score += 2
				} else if strings.Contains(kw, t) || strings.Contains(t, kw) {
					score++
				}
			}
		}
		if score > 0 {
			results = append(results, scored{ep: ep, score: score})
		}
	}
	sort.SliceStable(results, func(i, j int) bool { return results[i].score > results[j].score })
	if len(results) > limit {
		results = results[:limit]
	}

	out := make([]map[string]any, 0, len(results))
	for _, r := range results {
		item := codeOrchEndpointMetadata(r.ep)
		item["score"] = r.score
		out = append(out, item)
	}
	text, err := bound.JSON(map[string]any{"count": len(out), "results": out})
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding search results: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}

func handleCodeOrchGet(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call deutero_search first)"), nil
	}
	ep := findCodeOrchEndpoint(id)
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call deutero_search to discover valid ids", id)), nil
	}
	if ep.Method != "GET" {
		return mcplib.NewToolResultError(fmt.Sprintf("endpoint_id %q is %s, but deutero_get only permits GET endpoints", id, ep.Method)), nil
	}
	text, err := bound.JSON(codeOrchEndpointMetadata(ep))
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding endpoint metadata: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}

func handleCodeOrchExecute(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call deutero_search first)"), nil
	}

	ep := findCodeOrchEndpoint(id)
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call deutero_search to discover valid ids", id)), nil
	}

	params, _ := args["params"].(map[string]any)
	if params == nil {
		params = map[string]any{}
	}

	c, platformSession, err := newMCPClient(ctx)
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	if platformSession != nil {
		defer platformSession.ZeroCredentials()
	}
	if err := cli.AdoptMCPOutputSemantics(platformSession, params); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path := ep.Path
	for _, p := range ep.Positional {
		if v, ok := params[p]; ok && strings.Contains(path, "{"+p+"}") {
			path = strings.ReplaceAll(path, "{"+p+"}", mcpPathValue(v))
			delete(params, p)
		}
	}

	hdrs := make(map[string]string, len(ep.HeaderOverrides)+len(ep.HeaderParams))
	for k, v := range ep.HeaderOverrides {
		hdrs[k] = v
	}
	for _, binding := range ep.HeaderParams {
		if binding.Default != "" {
			hdrs[binding.WireName] = binding.Default
		}
		for _, key := range []string{binding.PublicName, binding.WireName} {
			if v, ok := params[key]; ok {
				hdrs[binding.WireName] = formatMCPParamValue(v)
				delete(params, key)
				break
			}
		}
	}
	if len(hdrs) == 0 {
		hdrs = nil
	}

	// Route params to their runtime slots. GET/DELETE params are query
	// strings; write methods split spec-declared query params from the
	// remaining params used as the request body below.
	query := map[string]string{}
	if ep.Method == "GET" || ep.Method == "DELETE" {
		for k, v := range params {
			query[codeOrchWireQueryName(ep.QueryParams, k)] = formatMCPParamValue(v)
		}
	} else {
		// Route spec-declared in:query params to the query string for write
		// methods too. Without this, a query param (e.g. sendToLedger on
		// PUT /ledger/voucher/{id}) wrongly lands in the JSON body and the
		// API silently ignores it or rejects the request. The remaining
		// params stay in the map for codeOrchWriteBody (the JSON body).
		if enc := codeOrchSplitQuery(ep.QueryParams, params); enc != "" {
			sep := "?"
			if strings.Contains(path, "?") {
				sep = "&"
			}
			path += sep + enc
		}
	}

	writeBody := func() any {
		if ep.BodyIsArray {
			return codeOrchArrayBody(params)
		}
		return codeOrchWriteBody(params)
	}
	var data json.RawMessage
	switch ep.Method {
	case "GET":
		if len(hdrs) > 0 {
			if ep.Mutating {
				data, err = c.GetMutatingWithHeaders(ctx, path, query, hdrs)
			} else {
				data, err = c.GetWithHeaders(ctx, path, query, hdrs)
			}
		} else {
			if ep.Mutating {
				data, err = c.GetMutating(ctx, path, query)
			} else {
				data, err = c.Get(ctx, path, query)
			}
		}
	case "DELETE":
		if len(hdrs) > 0 {
			data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, query, hdrs)
		} else {
			data, _, err = c.DeleteWithParams(ctx, path, query)
		}
	case "POST":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PostWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Post(ctx, path, body)
		}
	case "PUT":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PutWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Put(ctx, path, body)
		}
	case "PATCH":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PatchWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Patch(ctx, path, body)
		}
	default:
		return mcplib.NewToolResultError(fmt.Sprintf("unsupported method %q", ep.Method)), nil
	}
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	text := bound.EndpointResponse(ep.Method, data)
	if platformSession != nil {
		text = bound.WithMetadata(text, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(text), nil
}

// codeOrchWriteBody returns the value handed to the client layer as the
// request body for write methods (POST/PUT/PATCH). It MUST be the structured
// params map, never pre-marshaled bytes.
//
// client.do() marshals the body value exactly once. Handing it []byte makes
// json.Marshal([]byte) emit a base64-encoded JSON *string*, so the API
// receives "eyJ...==" where it expects the request object. Strict JSON APIs
// reject that as the wrong type at the body root. GET/DELETE carry no body,
// so this defect stays latent until the first write attempt.
func codeOrchWriteBody(params map[string]any) any {
	return params
}

// codeOrchArrayBody returns the request body for endpoints whose schema root
// is a bare top-level JSON array (ep.BodyIsArray). Such a body cannot be
// expressed as the params object, so the agent supplies the array under the
// conventional params key "body" (these endpoints have no flattened named
// params, so there is no collision risk). When present and array-shaped it is
// sent as the top-level array the API expects. Otherwise params is returned
// unchanged so a malformed call fails loudly at the API (HTTP 422) instead of
// silently sending the wrong shape or a partial write — financial mutations
// are never retried with body-variant guesses (broken-convenience guardrail).
func codeOrchArrayBody(params map[string]any) any {
	if v, ok := params["body"]; ok {
		if arr, ok := v.([]any); ok {
			return arr
		}
	}
	return params
}

// codeOrchSplitQuery removes spec-declared in:query params from params and
// returns them URL-encoded for appending to the request path. The remaining
// entries stay in the map for codeOrchWriteBody (the JSON body), so a write
// method's query parameters never get buried in the body. Mutates params by
// design (deletes the consumed query keys).
func codeOrchSplitQuery(queryParams []codeOrchParamBinding, params map[string]any) string {
	uv := neturl.Values{}
	for _, q := range queryParams {
		for _, key := range []string{q.PublicName, q.WireName} {
			if key == "" {
				continue
			}
			if v, ok := params[key]; ok {
				uv.Set(q.WireName, formatMCPParamValue(v))
				delete(params, key)
				break
			}
		}
	}
	return uv.Encode()
}

func codeOrchWireQueryName(queryParams []codeOrchParamBinding, name string) string {
	for _, q := range queryParams {
		if q.PublicName == name || q.WireName == name {
			return q.WireName
		}
	}
	return name
}
