// Copyright 2026 francis and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"runtime"
	"strings"
	"time"

	"github.com/deutero-ai/deutero-cli/internal/config"
	"github.com/spf13/cobra"
)

// Stytch Connected Apps browser-redirect (OAuth 2.0 + PKCE) login.
//
// Flow: mint a PKCE verifier/challenge, boot a loopback callback server on an
// OS-assigned port, open the browser to the connected-app authorize endpoint,
// receive the authorization code on the callback, exchange it at the OIDC token
// endpoint, and persist the resulting tokens via cfg.SaveTokens so AuthHeader()
// serves them as `Bearer <access_token>` (AuthSource "oauth2").
//
// Endpoints resolve from the login domain's OIDC discovery document
// ({domain}/.well-known/openid-configuration), so test vs prod is a single
// --domain switch and endpoint changes are picked up automatically. Both
// endpoints and every identifier are still overridable by flag/env. The token
// endpoint is standard OIDC: form-encoded body, `error`/`error_description`
// error shape. A client secret is optional (client_secret_post) — the discovery
// doc advertises `none`, so PKCE alone authenticates a public CLI client.
const (
	// defaultLoginDomain is Deutero's production Stytch login domain. Override
	// with --domain https://login-test.deutero.ai (or DEUTERO_OAUTH_DOMAIN) to
	// target the test project.
	defaultLoginDomain = "https://login.deutero.ai"
	// defaultScope requests offline_access (refresh token) plus the study-API
	// access scope the CLI needs to call Deutero on the user's behalf.
	defaultScope = "openid email offline_access full_access"
)

// oidcDiscovery is the subset of the OIDC discovery document we consume.
type oidcDiscovery struct {
	AuthorizationEndpoint string `json:"authorization_endpoint"`
	TokenEndpoint         string `json:"token_endpoint"`
}

// oauthTokenResponse covers both the OIDC success body and its RFC 6749 error
// body (`error`/`error_description`), plus the `status_code` Stytch echoes.
type oauthTokenResponse struct {
	AccessToken      string `json:"access_token"`
	ExpiresIn        int    `json:"expires_in"`
	RefreshToken     string `json:"refresh_token"`
	Scope            string `json:"scope"`
	TokenType        string `json:"token_type"`
	IDToken          string `json:"id_token"`
	StatusCode       int    `json:"status_code"`
	Error            string `json:"error"`
	ErrorDescription string `json:"error_description"`
	RequestID        string `json:"request_id"`
}

func newAuthLoginCmd(flags *rootFlags) *cobra.Command {
	var (
		clientID     string
		clientSecret string
		domain       string
		authorizeURL string
		tokenURL     string
		scope        string
		noLaunch     bool
		timeout      time.Duration
	)
	cmd := &cobra.Command{
		Use:   "login",
		Short: "Log in via your browser (Stytch Connected Apps, OAuth2 + PKCE)",
		Long: "Authenticate through your browser against a Stytch Connected App.\n" +
			"Opens the authorize page, captures the redirect on a loopback server,\n" +
			"exchanges the code for tokens, and saves them to your credentials file.\n\n" +
			"Endpoints are discovered from the login domain's OIDC document; point\n" +
			"--domain (or DEUTERO_OAUTH_DOMAIN) at the test project to switch envs.\n\n" +
			"Required:\n" +
			"  --client-id  / DEUTERO_OAUTH_CLIENT_ID   (Connected App client ID)\n" +
			"Optional:\n" +
			"  --client-secret / DEUTERO_OAUTH_CLIENT_SECRET (confidential clients)\n" +
			"  --domain        / DEUTERO_OAUTH_DOMAIN        (default " + defaultLoginDomain + ")",
		Example: "  deutero-pp-cli auth login --client-id CLIENT_ID\n" +
			"  deutero-pp-cli auth login --client-id CLIENT_ID --domain https://login-test.deutero.ai\n" +
			"  deutero-pp-cli auth login --no-launch   # print the URL instead of opening a browser",
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			clientID = firstNonEmpty(clientID, envValue("DEUTERO_OAUTH_CLIENT_ID"))
			clientSecret = firstNonEmpty(clientSecret, envValue("DEUTERO_OAUTH_CLIENT_SECRET"))
			domain = firstNonEmpty(domain, envValue("DEUTERO_OAUTH_DOMAIN"), defaultLoginDomain)
			authorizeURL = firstNonEmpty(authorizeURL, envValue("DEUTERO_OAUTH_AUTHORIZE_URL"))
			tokenURL = firstNonEmpty(tokenURL, envValue("DEUTERO_OAUTH_TOKEN_URL"))
			scope = firstNonEmpty(scope, envValue("DEUTERO_OAUTH_SCOPE"), defaultScope)

			if clientID == "" {
				return usageErr(fmt.Errorf("--client-id is required (or set DEUTERO_OAUTH_CLIENT_ID)"))
			}

			// Fill any endpoint not explicitly overridden from OIDC discovery.
			if authorizeURL == "" || tokenURL == "" {
				disc, err := fetchOIDCDiscovery(cmd.Context(), domain)
				if err != nil {
					return configErr(fmt.Errorf("discovering OAuth endpoints from %s: %w", domain, err))
				}
				authorizeURL = firstNonEmpty(authorizeURL, disc.AuthorizationEndpoint)
				tokenURL = firstNonEmpty(tokenURL, disc.TokenEndpoint)
			}
			if authorizeURL == "" || tokenURL == "" {
				return configErr(fmt.Errorf("could not resolve authorize/token endpoints; pass --authorize-url and --token-url"))
			}

			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			return runBrowserLogin(cmd, flags, cfg, browserLoginParams{
				clientID:     clientID,
				clientSecret: clientSecret,
				authorizeURL: authorizeURL,
				tokenURL:     tokenURL,
				scope:        scope,
				noLaunch:     noLaunch || flags.noInput,
				timeout:      timeout,
			})
		},
	}

	cmd.Flags().StringVar(&clientID, "client-id", "", "Stytch Connected App OAuth client ID (env DEUTERO_OAUTH_CLIENT_ID)")
	cmd.Flags().StringVar(&clientSecret, "client-secret", "", "OAuth client secret for confidential clients; omit for PKCE-only (env DEUTERO_OAUTH_CLIENT_SECRET)")
	cmd.Flags().StringVar(&domain, "domain", "", "Login domain whose OIDC document supplies the endpoints (env DEUTERO_OAUTH_DOMAIN, default "+defaultLoginDomain+")")
	cmd.Flags().StringVar(&authorizeURL, "authorize-url", "", "Override the authorize endpoint (env DEUTERO_OAUTH_AUTHORIZE_URL)")
	cmd.Flags().StringVar(&tokenURL, "token-url", "", "Override the token endpoint (env DEUTERO_OAUTH_TOKEN_URL)")
	cmd.Flags().StringVar(&scope, "scope", "", "OAuth scopes, space-separated (env DEUTERO_OAUTH_SCOPE, default \""+defaultScope+"\")")
	cmd.Flags().BoolVar(&noLaunch, "no-launch", false, "Print the authorize URL instead of opening a browser")
	cmd.Flags().DurationVar(&timeout, "timeout", 5*time.Minute, "How long to wait for the browser callback")
	return cmd
}

type browserLoginParams struct {
	clientID     string
	clientSecret string
	authorizeURL string
	tokenURL     string
	scope        string
	noLaunch     bool
	timeout      time.Duration
}

func runBrowserLogin(cmd *cobra.Command, flags *rootFlags, cfg *config.Config, p browserLoginParams) error {
	w := cmd.OutOrStdout()
	errw := cmd.ErrOrStderr()

	// Loopback listener on an OS-assigned port; the bound port becomes the
	// registered redirect URI. Hold the listener (don't close-then-reopen) to
	// avoid racing another process onto the same port.
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return configErr(fmt.Errorf("starting callback server: %w", err))
	}
	port := ln.Addr().(*net.TCPAddr).Port
	redirectURI := fmt.Sprintf("http://127.0.0.1:%d/callback", port)

	verifier, err := generatePKCEVerifier()
	if err != nil {
		return configErr(fmt.Errorf("generating PKCE verifier: %w", err))
	}
	challenge := pkceChallenge(verifier)
	state, err := randomURLToken(24)
	if err != nil {
		return configErr(fmt.Errorf("generating state: %w", err))
	}

	params := url.Values{}
	params.Set("client_id", p.clientID)
	params.Set("redirect_uri", redirectURI)
	params.Set("response_type", "code")
	params.Set("code_challenge", challenge)
	params.Set("code_challenge_method", "S256")
	params.Set("scope", p.scope)
	params.Set("state", state)
	authURL := p.authorizeURL + "?" + params.Encode()

	// Per-login mux (never the global DefaultServeMux) so repeated invocations
	// in one process don't collide on a duplicate route registration.
	type callbackResult struct {
		code string
		err  error
	}
	resultCh := make(chan callbackResult, 1)
	mux := http.NewServeMux()
	mux.HandleFunc("/callback", func(rw http.ResponseWriter, r *http.Request) {
		q := r.URL.Query()
		if e := q.Get("error"); e != "" {
			desc := q.Get("error_description")
			writeCallbackPage(rw, false, strings.TrimSpace(e+": "+desc))
			resultCh <- callbackResult{err: fmt.Errorf("authorization denied: %s %s", e, desc)}
			return
		}
		if got := q.Get("state"); got != state {
			writeCallbackPage(rw, false, "state mismatch")
			resultCh <- callbackResult{err: fmt.Errorf("state mismatch: possible CSRF, aborting")}
			return
		}
		code := q.Get("code")
		if code == "" {
			writeCallbackPage(rw, false, "no authorization code in callback")
			resultCh <- callbackResult{err: fmt.Errorf("no authorization code in callback")}
			return
		}
		writeCallbackPage(rw, true, "")
		resultCh <- callbackResult{code: code}
	})

	server := &http.Server{Handler: mux, ReadHeaderTimeout: 10 * time.Second}
	go func() {
		if serveErr := server.Serve(ln); serveErr != nil && serveErr != http.ErrServerClosed {
			resultCh <- callbackResult{err: serveErr}
		}
	}()
	defer func() {
		ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		defer cancel()
		_ = server.Shutdown(ctx)
	}()

	if p.noLaunch {
		fmt.Fprintln(errw, "Open this URL in your browser to authenticate:")
		fmt.Fprintln(errw, "  "+authURL)
	} else {
		fmt.Fprintln(errw, "Opening your browser to authenticate...")
		if openErr := openBrowser(authURL); openErr != nil {
			fmt.Fprintln(errw, "Could not open a browser automatically. Open this URL manually:")
			fmt.Fprintln(errw, "  "+authURL)
		}
	}

	var code string
	select {
	case res := <-resultCh:
		if res.err != nil {
			return authErr(res.err)
		}
		code = res.code
	case <-time.After(p.timeout):
		return authErr(fmt.Errorf("timed out after %s waiting for the browser callback", p.timeout))
	}

	tok, err := exchangeCodeForToken(cmd.Context(), tokenExchange{
		tokenURL:     p.tokenURL,
		clientID:     p.clientID,
		clientSecret: p.clientSecret,
		code:         code,
		verifier:     verifier,
		redirectURI:  redirectURI,
	})
	if err != nil {
		return authErr(err)
	}

	var expiry time.Time
	if tok.ExpiresIn > 0 {
		expiry = time.Now().Add(time.Duration(tok.ExpiresIn) * time.Second)
	}
	// Persist the client secret alongside so a later refresh flow can
	// re-authenticate confidential clients; empty for PKCE-only logins.
	if err := cfg.SaveTokens(p.clientID, p.clientSecret, tok.AccessToken, tok.RefreshToken, expiry); err != nil {
		return configErr(fmt.Errorf("saving tokens: %w", err))
	}

	if flags.asJSON {
		out := map[string]any{
			"authenticated": true,
			"token_type":    tok.TokenType,
			"has_refresh":   tok.RefreshToken != "",
			"config_path":   cfg.Path,
			"token_storage": cfg.TokenStorage,
		}
		if !expiry.IsZero() {
			out["expires_at"] = expiry.UTC().Format(time.RFC3339)
		}
		return printJSONFiltered(w, out, flags)
	}

	fmt.Fprintln(w, green("Logged in."))
	if cfg.TokenStorage == "keyring" {
		fmt.Fprintln(w, "  Access/refresh token saved to your OS keyring.")
		fmt.Fprintf(w, "  Non-secret bookkeeping (client id, token expiry) saved to %s\n", credentialSavePath(cfg))
	} else {
		fmt.Fprintf(w, "  Credentials saved to %s\n", credentialSavePath(cfg))
	}
	if !expiry.IsZero() {
		fmt.Fprintf(w, "  Access token expires %s\n", expiry.Format(time.RFC1123))
	}
	if tok.RefreshToken == "" {
		fmt.Fprintln(w, yellow("  No refresh token returned; you'll need to log in again when it expires."))
	}
	return nil
}

// fetchOIDCDiscovery reads {domain}/.well-known/openid-configuration and returns
// its authorize/token endpoints.
func fetchOIDCDiscovery(ctx context.Context, domain string) (*oidcDiscovery, error) {
	discURL := strings.TrimRight(domain, "/") + "/.well-known/openid-configuration"
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, discURL, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", "application/json")
	resp, err := (&http.Client{Timeout: 15 * time.Second}).Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("HTTP %d from %s", resp.StatusCode, discURL)
	}
	body, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return nil, err
	}
	var disc oidcDiscovery
	if err := json.Unmarshal(body, &disc); err != nil {
		return nil, fmt.Errorf("parsing discovery document: %w", err)
	}
	if disc.AuthorizationEndpoint == "" || disc.TokenEndpoint == "" {
		return nil, fmt.Errorf("discovery document missing authorize/token endpoints")
	}
	return &disc, nil
}

type tokenExchange struct {
	tokenURL     string
	clientID     string
	clientSecret string
	code         string
	verifier     string
	redirectURI  string
}

// exchangeCodeForToken POSTs the authorization code to the OIDC token endpoint
// (RFC 6749 form-encoded body) and returns the parsed token response. A client
// secret, when present, is sent via client_secret_post; otherwise the exchange
// authenticates with PKCE alone.
func exchangeCodeForToken(ctx context.Context, tx tokenExchange) (*oauthTokenResponse, error) {
	form := url.Values{}
	form.Set("grant_type", "authorization_code")
	form.Set("client_id", tx.clientID)
	form.Set("code", tx.code)
	form.Set("code_verifier", tx.verifier)
	form.Set("redirect_uri", tx.redirectURI)
	if tx.clientSecret != "" {
		form.Set("client_secret", tx.clientSecret)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, tx.tokenURL, strings.NewReader(form.Encode()))
	if err != nil {
		return nil, fmt.Errorf("building token request: %w", err)
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	req.Header.Set("Accept", "application/json")

	resp, err := (&http.Client{Timeout: 30 * time.Second}).Do(req)
	if err != nil {
		return nil, fmt.Errorf("token exchange request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if err != nil {
		return nil, fmt.Errorf("reading token response: %w", err)
	}
	var tr oauthTokenResponse
	if err := json.Unmarshal(respBody, &tr); err != nil {
		return nil, fmt.Errorf("token endpoint returned unparseable response (HTTP %d)", resp.StatusCode)
	}
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		if tr.Error != "" {
			msg := tr.Error
			if tr.ErrorDescription != "" {
				msg += ": " + tr.ErrorDescription
			}
			return nil, fmt.Errorf("token exchange rejected: %s", msg)
		}
		return nil, fmt.Errorf("token exchange failed: HTTP %d", resp.StatusCode)
	}
	if tr.AccessToken == "" {
		return nil, fmt.Errorf("token endpoint returned no access token")
	}
	return &tr, nil
}

// generatePKCEVerifier returns a high-entropy code verifier (RFC 7636).
func generatePKCEVerifier() (string, error) {
	return randomURLToken(32)
}

// pkceChallenge derives the S256 code challenge from a verifier.
func pkceChallenge(verifier string) string {
	sum := sha256.Sum256([]byte(verifier))
	return base64.RawURLEncoding.EncodeToString(sum[:])
}

func randomURLToken(nBytes int) (string, error) {
	b := make([]byte, nBytes)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

// writeCallbackPage renders the browser landing page shown after the redirect.
func writeCallbackPage(w http.ResponseWriter, ok bool, detail string) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	if ok {
		_, _ = io.WriteString(w, "<!doctype html><title>Authenticated</title>"+
			"<body style=\"font-family:system-ui;padding:3rem;text-align:center\">"+
			"<h2>Authentication successful</h2><p>You can close this window and return to your terminal.</p></body>")
		return
	}
	w.WriteHeader(http.StatusBadRequest)
	_, _ = io.WriteString(w, "<!doctype html><title>Authentication failed</title>"+
		"<body style=\"font-family:system-ui;padding:3rem;text-align:center\">"+
		"<h2>Authentication failed</h2><p>"+detail+"</p></body>")
}

// firstNonEmpty returns the first non-empty (post-trim) value, or "".
func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		if strings.TrimSpace(v) != "" {
			return strings.TrimSpace(v)
		}
	}
	return ""
}

// envValue reads and trims an environment variable.
func envValue(key string) string {
	return strings.TrimSpace(os.Getenv(key))
}

// openBrowser opens url in the OS default browser without blocking.
func openBrowser(target string) error {
	var name string
	var args []string
	switch runtime.GOOS {
	case "darwin":
		name, args = "open", []string{target}
	case "windows":
		name, args = "rundll32", []string{"url.dll,FileProtocolHandler", target}
	default:
		name, args = "xdg-open", []string{target}
	}
	return exec.Command(name, args...).Start()
}
