// Copyright 2026 francis and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// learn_init.go is the spec-driven init shim for the self-learning loop.
// newLearnConfig builds the per-CLI *entities.Config the cobra teach /
// recall / learnings commands thread through every call site;
// initLearn seeds the entity_lookups table from the canonical-+-aliases
// table declared in spec.Learn.EntityLookupSeeds. Both run once at
// startup; subsequent calls are idempotent (INSERT OR IGNORE on the
// store side, fresh Config build on the registration side).
//
// Soft validation: a runtime regex compile failure (which spec parse
// already rejects at load time) logs to stderr and continues without
// the pattern instead of aborting the CLI. Empty Learn config produces
// a Config with built-in stopwords and a no-op initLearn.

package cli

import (
	"context"
	"database/sql"
	"fmt"
	"os"
	"sync"

	"github.com/deutero-ai/deutero-cli/internal/learn/entities"
	"github.com/deutero-ai/deutero-cli/internal/store"
)

// newLearnConfig returns the per-CLI entity extractor Config the
// teach / recall / normalize call sites pass into the learn package.
// Reads the printed-CLI's spec.Learn.TickerPatterns, Stopwords, and
// Synonyms; patterns that fail to compile at runtime (defense in
// depth — spec parse already validated them) log a warning and are
// skipped. Declared synonyms register on both the returned Config and
// the store package's write-side normalizer.
func newLearnConfig() *entities.Config {
	cfg := entities.NewConfig()
	return cfg
}

// initLearn seeds the entity_lookups table from the spec.Learn.
// EntityLookupSeeds declaration. INSERT OR IGNORE on the store side
// makes this idempotent — calling it twice produces the same DB state
// as calling it once. An empty seed map is a no-op (returns nil).
func initLearn(ctx context.Context, db *sql.DB) error {
	_ = ctx
	_ = db
	return nil
}

// learnInitOnce gates runLearnInitOnce so the seed pass happens at
// most once per CLI process. The sync.Once keeps the cost off the
// hot path for repeat command invocations within an MCP session.
var learnInitOnce sync.Once

// runLearnInitOnce opens the canonical store path, fires initLearn
// once per process, and downgrades any failure to a stderr warning.
// Per the self-learning loop's soft-validation contract, a seed
// failure must never abort the CLI — the recall path returns the
// empty envelope if entity_lookups is missing rows, which is the
// same behavior an opt-out CLI sees.
func runLearnInitOnce(ctx context.Context) {
	learnInitOnce.Do(func() {
		dbPath := defaultDBPath("deutero-pp-cli")
		s, err := store.OpenWithContext(ctx, dbPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warning: deutero-pp-cli: learn init: open store: %v\n", err)
			return
		}
		defer s.Close()
		if err := initLearn(ctx, s.DB()); err != nil {
			fmt.Fprintf(os.Stderr, "warning: deutero-pp-cli: learn init: %v\n", err)
		}
	})
}

// learnCommonIdentityFields is the ordered, domain-neutral list
// ResourceEntitiesFromJSON walks when a resource has no more specific
// identity key. Missing JSON keys are skipped, so one list can serve
// every collection.
var learnCommonIdentityFields = []string{
	"name", "title", "display_name", "full_name", "short_name", "label",
	"slug", "key", "code", "id", "address",
}

// learnResourceTypeFields returns the per-resource identity-field map
// passed to Recall so entity_match can be exact when the stored JSON
// actually carries the identity.
func learnResourceTypeFields() map[string][]string {
	return map[string][]string{
		"analysis":             {"optimal_k", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"characteristics":      {"id", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "address"},
		"credits":              {"available_credits", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"deliveries":           {"id", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "address"},
		"embed":                {"study_id", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"fetches-and-signals":  {"interview_id", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"graph":                {"study_id", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"health":               {"name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"interviews":           {"id", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "address"},
		"personas":             {"id", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "address"},
		"projects":             {"id", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "address"},
		"questions":            {"id", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "address"},
		"recruitment":          {"study_id", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"rotate-secret":        {"signing_secret", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"screening":            {"id", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "address"},
		"search":               {"message_id", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"simulations":          {"id", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "address"},
		"stats":                {"study_id", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"studies":              {"id", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "address"},
		"transcript":           {"interview_id", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"transcripts":          {"interview_id", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"webhooks":             {"signing_secret", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"webhooks-event-types": {"envelope", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "id", "address"},
		"welcome":              {"id", "name", "title", "display_name", "full_name", "short_name", "label", "slug", "key", "code", "address"},
	}
}

// learnIdentityFieldsFor returns the identity fields for one resource
// type, falling back to the common list when the type is unknown.
func learnIdentityFieldsFor(resourceType string) []string {
	if fields, ok := learnResourceTypeFields()[resourceType]; ok && len(fields) > 0 {
		return fields
	}
	return append([]string(nil), learnCommonIdentityFields...)
}
