// Copyright 2026 francis and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newProjectsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "projects",
		Short:       "Containers that group studies.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newProjectsCreateCmd(flags))
	cmd.AddCommand(newProjectsGetCmd(flags))
	cmd.AddCommand(newProjectsListCmd(flags))
	cmd.AddCommand(newProjectsUpdateCmd(flags))
	cmd.AddCommand(newProjectsStudiesCmd(flags))
	return cmd
}
