// Copyright 2026 francis and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newStudiesScreeningCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "screening",
		Short:       "Qualifying questions and disqualification behavior.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newStudiesScreeningCreateCmd(flags))
	cmd.AddCommand(newStudiesScreeningDeleteCmd(flags))
	cmd.AddCommand(newStudiesScreeningGetCmd(flags))
	cmd.AddCommand(newStudiesScreeningReorderQuestionsCmd(flags))
	cmd.AddCommand(newStudiesScreeningSetSettingsCmd(flags))
	cmd.AddCommand(newStudiesScreeningUpdateCmd(flags))
	return cmd
}
