// Copyright 2026 francis and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newStudiesSearchTranscriptsCmd(flags *rootFlags) *cobra.Command {
	var flagQ string
	var flagMode string
	var flagQuestionId string
	var flagCompletedOnly bool
	var flagIncludeSimulated bool
	var flagExternalParticipantId string
	var flagStrict bool
	var flagLimit int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "transcripts <study_id>",
		Aliases:     []string{"get"},
		Short:       "Search participant answers in a study.",
		Example:     "  deutero-pp-cli studies search transcripts f0ed9214-06fc-4420-87b3-31240b670fc1 --q pricing --mode semantic",
		Annotations: map[string]string{"pp:endpoint": "search.transcripts", "pp:method": "GET", "pp:path": "/api/v1/studies/{study_id}/search", "mcp:read-only": "true", "pp:requires-input": "true", "pp:happy-args": "study_id=f0ed9214-06fc-4420-87b3-31240b670fc1;--q=pricing"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <study_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <study_id>"))
			}
			if !cmd.Flags().Changed("q") && flagQ == "" && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "q")
			}
			path := "/api/v1/studies/{study_id}/search"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("study_id is required\nUsage: %s <%s>", cmd.CommandPath(), "study_id"))
			}
			path = replacePathParam(path, "study_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "live", "search", path, retainCLIQueryParams(cmd, map[string]string{
				"q":                       formatCLIParamValue(flagQ),
				"mode":                    formatCLIParamValue(flagMode),
				"question_id":             formatCLIParamValue(flagQuestionId),
				"completed_only":          formatCLIParamValue(flagCompletedOnly),
				"include_simulated":       formatCLIParamValue(flagIncludeSimulated),
				"external_participant_id": formatCLIParamValue(flagExternalParticipantId),
				"strict":                  formatCLIParamValue(flagStrict),
				"limit":                   formatCLIParamValue(flagLimit),
			}, map[string][]string{"q": {"q"}, "mode": {"mode"}, "question_id": {"question-id"}, "completed_only": {"completed-only"}, "include_simulated": {"include-simulated"}, "external_participant_id": {"external-participant-id"}, "strict": {"strict"}, "limit": {"limit"}}, "", "offset"), nil, flagAll, "", "offset", "limit", 20, "", "", "hits", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := collectionItemsForOutput(data, path)
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(outputData, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				var selectErr error
				filtered := data
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered, map[string]bool{"external_participant_id": true, "interview_id": true, "message_id": true, "node_id": true, "participant_id": true, "participant_name": true, "question_id": true, "score": true})
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				wrapped, wrapErr = wrapPlatformStructuredOutput(wrapped, flags, "results", true)
				if wrapErr != nil {
					return wrapErr
				}
				if err := printOutput(cmd.OutOrStdout(), wrapped, true); err != nil {
					return err
				}
				return selectErr
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, map[string]bool{"external_participant_id": true, "interview_id": true, "message_id": true, "node_id": true, "participant_id": true, "participant_name": true, "question_id": true, "score": true})
		},
	}
	cmd.Flags().StringVar(&flagQ, "q", "", "Search query")
	cmd.Flags().StringVar(&flagMode, "mode", "hybrid", "Mode")
	cmd.Flags().StringVar(&flagQuestionId, "question-id", "", "Restrict to one question.")
	cmd.Flags().BoolVar(&flagCompletedOnly, "completed-only", false, "Only completed interviews")
	cmd.Flags().BoolVar(&flagIncludeSimulated, "include-simulated", false, "Include simulated interviews")
	cmd.Flags().StringVar(&flagExternalParticipantId, "external-participant-id", "", "Restrict to the interviews of one person, named by your own id for them (the entry link's ?")
	cmd.Flags().BoolVar(&flagStrict, "strict", false, "hybrid mode: fail (503) instead of silently degrading to string search when semantic search is unavailable")
	cmd.Flags().IntVar(&flagLimit, "limit", 20, "Limit")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
