// Copyright 2026 francis and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newStudiesGraphCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "graph",
		Short:       "Get, create, and update graph for studies",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newStudiesGraphActivateCmd(flags))
	cmd.AddCommand(newStudiesGraphCheckCmd(flags))
	cmd.AddCommand(newStudiesGraphDeactivateCmd(flags))
	cmd.AddCommand(newStudiesGraphGetCmd(flags))
	cmd.AddCommand(newStudiesGraphGetFlowSignalsCmd(flags))
	cmd.AddCommand(newStudiesGraphImportQuestionsToCmd(flags))
	cmd.AddCommand(newStudiesGraphPatchCmd(flags))
	cmd.AddCommand(newStudiesGraphSetCmd(flags))
	return cmd
}
