// Copyright 2026 francis and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newStudiesInterviewsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "interviews",
		Short:       "List and find interviews for studies",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newStudiesInterviewsFindByExternalIdCmd(flags))
	cmd.AddCommand(newStudiesInterviewsListCmd(flags))
	return cmd
}
