// Copyright 2026 francis and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newStudiesCharacteristicsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "characteristics",
		Short:       "Participant attribute questions collected before the interview.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newStudiesCharacteristicsCreateCmd(flags))
	cmd.AddCommand(newStudiesCharacteristicsDeleteCmd(flags))
	cmd.AddCommand(newStudiesCharacteristicsGetCmd(flags))
	cmd.AddCommand(newStudiesCharacteristicsReorderQuestionsCmd(flags))
	cmd.AddCommand(newStudiesCharacteristicsSetSettingsCmd(flags))
	cmd.AddCommand(newStudiesCharacteristicsUpdateCmd(flags))
	return cmd
}
