// Copyright 2026 francis and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newStudiesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "studies",
		Short:       "Study creation and core configuration.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newStudiesCreateCmd(flags))
	cmd.AddCommand(newStudiesGetStudyCmd(flags))
	cmd.AddCommand(newStudiesUpdateCmd(flags))
	cmd.AddCommand(newStudiesAnalysisCmd(flags))
	cmd.AddCommand(newStudiesCharacteristicsCmd(flags))
	cmd.AddCommand(newStudiesEmbedCmd(flags))
	cmd.AddCommand(newStudiesGraphCmd(flags))
	cmd.AddCommand(newStudiesInterviewsCmd(flags))
	cmd.AddCommand(newStudiesPersonasCmd(flags))
	cmd.AddCommand(newStudiesQuestionsCmd(flags))
	cmd.AddCommand(newStudiesRecruitmentCmd(flags))
	cmd.AddCommand(newStudiesScreeningCmd(flags))
	cmd.AddCommand(newStudiesSearchCmd(flags))
	cmd.AddCommand(newStudiesSimulationsCmd(flags))
	cmd.AddCommand(newStudiesStatsCmd(flags))
	cmd.AddCommand(newStudiesTranscriptsCmd(flags))
	cmd.AddCommand(newStudiesWelcomeCmd(flags))
	return cmd
}
