// Copyright 2026 francis and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"os"

	"github.com/spf13/cobra"
)

func newStudiesCreateCmd(flags *rootFlags) *cobra.Command {
	var bodyAnonymous bool
	var bodyBenefits string
	var bodyDescription string
	var bodyInstitution string
	var bodyLanguage string
	var bodyMaxResponses string
	var bodyMethodology string
	var bodyModelTier string
	var bodyName string
	var bodyObjectives string
	var bodyProjectId string
	var bodyRedirectUrl string
	var bodyResearchQuestion string
	var bodyRisks string
	var bodySupportContact string
	var bodySurveyType string
	var bodyTargetPopulation string
	var bodyVideoEnabled bool
	var bodyVoiceEnabled bool
	var stdinBody bool

	cmd := &cobra.Command{
		Use:         "create",
		Short:       "Create a new study inside a project.",
		Example:     "  deutero-pp-cli studies create --project-id be8fc6bf-8819-4f73-81f9-961cf751b13a --name \"Example study\"",
		Annotations: map[string]string{"pp:endpoint": "studies.create", "pp:method": "POST", "pp:path": "/api/v1/studies", "pp:requires-input": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !stdinBody {
				if !cmd.Flags().Changed("name") && bodyName == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "name")
				}
				if !cmd.Flags().Changed("project-id") && bodyProjectId == "" && !flags.dryRun {
					return fmt.Errorf("required flag \"%s\" not set", "project-id")
				}
			}
			path := "/api/v1/studies"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			var body any
			if stdinBody {
				stdinData, err := io.ReadAll(os.Stdin)
				if err != nil {
					return fmt.Errorf("reading stdin: %w", err)
				}
				var jsonBody map[string]any
				if err := json.Unmarshal(stdinData, &jsonBody); err != nil {
					return fmt.Errorf("parsing stdin JSON: %w", err)
				}
				body = jsonBody
			} else {
				bodyMap := map[string]any{}
				body = bodyMap
				if cmd.Flags().Changed("anonymous") {
					bodyMap["anonymous"] = bodyAnonymous
				}
				if cmd.Flags().Changed("benefits") || bodyBenefits != "" {
					bodyMap["benefits"] = bodyBenefits
				}
				if cmd.Flags().Changed("description") || bodyDescription != "" {
					bodyMap["description"] = bodyDescription
				}
				if cmd.Flags().Changed("institution") || bodyInstitution != "" {
					bodyMap["institution"] = bodyInstitution
				}
				if cmd.Flags().Changed("language") || bodyLanguage != "" {
					bodyMap["language"] = bodyLanguage
				}
				if cmd.Flags().Changed("max-responses") || bodyMaxResponses != "" {
					bodyMap["max_responses"] = bodyMaxResponses
				}
				if cmd.Flags().Changed("methodology") || bodyMethodology != "" {
					bodyMap["methodology"] = bodyMethodology
				}
				if cmd.Flags().Changed("model-tier") || bodyModelTier != "" {
					bodyMap["model_tier"] = bodyModelTier
				}
				if cmd.Flags().Changed("name") || bodyName != "" {
					bodyMap["name"] = bodyName
				}
				if cmd.Flags().Changed("objectives") || bodyObjectives != "" {
					bodyMap["objectives"] = bodyObjectives
				}
				if cmd.Flags().Changed("project-id") || bodyProjectId != "" {
					bodyMap["project_id"] = bodyProjectId
				}
				if cmd.Flags().Changed("redirect-url") || bodyRedirectUrl != "" {
					bodyMap["redirect_url"] = bodyRedirectUrl
				}
				if cmd.Flags().Changed("research-question") || bodyResearchQuestion != "" {
					bodyMap["research_question"] = bodyResearchQuestion
				}
				if cmd.Flags().Changed("risks") || bodyRisks != "" {
					bodyMap["risks"] = bodyRisks
				}
				if cmd.Flags().Changed("support-contact") || bodySupportContact != "" {
					bodyMap["support_contact"] = bodySupportContact
				}
				if cmd.Flags().Changed("survey-type") || bodySurveyType != "" {
					bodyMap["survey_type"] = bodySurveyType
				}
				if cmd.Flags().Changed("target-population") || bodyTargetPopulation != "" {
					bodyMap["target_population"] = bodyTargetPopulation
				}
				if cmd.Flags().Changed("video-enabled") {
					bodyMap["video_enabled"] = bodyVideoEnabled
				}
				if cmd.Flags().Changed("voice-enabled") {
					bodyMap["voice_enabled"] = bodyVoiceEnabled
				}
			}
			data, statusCode, err := c.PostWithParams(cmd.Context(), path, params, body)
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			// Inspect the mutate response body for a partial-failure-shaped
			// field (e.g. Google Ads `partialFailureError`). Several Google
			// APIs return 200 OK with a partial-failure field when some
			// operations in the batch failed; ignoring it silently swallows
			// real failures. Detection runs before output-mode selection so
			// the exit code is consistent regardless of how stdout is
			// rendered. --dry-run short-circuits because no real request
			// was sent.
			var partialFailure *partialFailureReport
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 {
				partialFailure = detectPartialFailure(data)
				if partialFailure != nil {
					fmt.Fprintf(os.Stderr, "warning: partial failure detected in %s response: %s\n", "studies", partialFailure.Message)
					if len(partialFailure.ResourceNames) > 0 {
						fmt.Fprintf(os.Stderr, "         succeeded: %d operation(s)\n", len(partialFailure.ResourceNames))
					}
				}
			}
			if !flags.dryRun && statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure) {
				writeMutationResponseToStore(cmd.Context(), "studies", data, "")
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				// Check if response contains an array (directly or wrapped in "data")
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
					} else {
						if partialFailure != nil && !flags.allowPartialFailure {
							return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "studies", partialFailure.Message))
						}
						return nil
					}
				} else {
					var wrapped struct {
						Data []map[string]any `json:"data"`
					}
					if json.Unmarshal(data, &wrapped) == nil && len(wrapped.Data) > 0 {
						if err := printAutoTable(cmd.OutOrStdout(), wrapped.Data); err != nil {
							fmt.Fprintf(os.Stderr, "warning: table rendering failed, falling back to JSON: %v\n", err)
						} else {
							if partialFailure != nil && !flags.allowPartialFailure {
								return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "studies", partialFailure.Message))
							}
							return nil
						}
					}
				}
			}
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				if flags.quiet {
					if partialFailure != nil && !flags.allowPartialFailure {
						return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "studies", partialFailure.Message))
					}
					return nil
				}
				envelope := map[string]any{
					"action":   "post",
					"resource": "studies",
					"path":     path,
					"status":   statusCode,
					"success":  statusCode >= 200 && statusCode < 300 && (partialFailure == nil || flags.allowPartialFailure),
				}
				if flags.agent {
					envelope["meta"] = map[string]any{"source": "live"}
				}
				if partialFailure != nil {
					envelope["partial_failure"] = partialFailure
				}
				if flags.dryRun {
					envelope["dry_run"] = true
					envelope["status"] = 0
					envelope["success"] = false
				}
				// Verify-mode synthetic envelope detection runs against RAW data
				// (before --compact/--select filtering) so the sentinel field is
				// guaranteed to be visible even if the operator passes a filter
				// flag that would otherwise strip it. Surfaces a top-level
				// verify_noop signal + flips success to false. Mirrors the dry_run
				// shape above.
				if len(data) > 0 {
					var rawParsed any
					if err := json.Unmarshal(data, &rawParsed); err == nil {
						if m, ok := rawParsed.(map[string]any); ok {
							if v, ok := m["__pp_verify_synthetic__"].(bool); ok && v {
								envelope["verify_noop"] = true
								envelope["success"] = false
							}
						}
					}
				}
				// Mutation-riding reads (POST search, RPC-over-POST lists) return
				// the same single-key collection envelopes as GET reads. Unwrap
				// before filtering so rows nest once under the result key and
				// --select filters rows, not envelope keys; plain created-object
				// responses pass through unwrapSingleKeyArray untouched.
				// Apply --compact and --select to the API response before wrapping.
				// --select wins when both are set: explicit field choice trumps the
				// generic high-gravity allow-list. Otherwise --compact still applies
				// when --agent is on but the user did not name fields.
				var selectErr error
				filtered := unwrapSingleKeyArray(data)
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered, map[string]bool{"characteristics_question_count": true, "dashboard_url": true, "id": true, "language": true, "model_id": true, "name": true, "participation_url": true, "project_id": true, "question_count": true, "redirect_url": true, "screening_question_count": true, "short_participation_url": true, "short_video_participation_url": true, "short_voice_participation_url": true, "video_participation_url": true, "voice_participation_url": true})
				}
				if len(filtered) > 0 {
					var parsed any
					if err := json.Unmarshal(filtered, &parsed); err == nil {
						if flags.agent {
							envelope["results"] = parsed
						} else {
							envelope["data"] = parsed
						}
					}
				}
				envelopeJSON, err := json.Marshal(envelope)
				if err != nil {
					return err
				}
				resultKey := "data"
				if flags.agent {
					resultKey = "results"
				}
				structured, err := wrapPlatformStructuredOutput(json.RawMessage(envelopeJSON), flags, resultKey, true)
				if err != nil {
					return err
				}
				if perr := printOutput(cmd.OutOrStdout(), structured, true); perr != nil {
					return perr
				}
				if partialFailure != nil && !flags.allowPartialFailure {
					return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "studies", partialFailure.Message))
				}
				return selectErr
			}
			// Fall-through for mutate paths that did not hit the table or
			// asJSON branches: --quiet, --csv, --plain, and default terminal
			// raw output. printOutputWithFlagsMeta renders the body with live
			// provenance, then the typed partial-failure exit fires unless
			// --allow-partial-failure downgrades it. Without this guard a
			// partial failure would exit 0 for these output modes — the exact
			// silent-swallow regression the surrounding patch is preventing
			// for asJSON / piped output.
			printErr := printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"}, map[string]bool{"characteristics_question_count": true, "dashboard_url": true, "id": true, "language": true, "model_id": true, "name": true, "participation_url": true, "project_id": true, "question_count": true, "redirect_url": true, "screening_question_count": true, "short_participation_url": true, "short_video_participation_url": true, "short_voice_participation_url": true, "video_participation_url": true, "voice_participation_url": true})
			if partialFailure != nil && !flags.allowPartialFailure {
				return partialFailureErr(fmt.Errorf("partial failure in %s response: %s", "studies", partialFailure.Message))
			}
			return printErr
		},
	}
	cmd.Flags().BoolVar(&bodyAnonymous, "anonymous", false, "Skip collecting participant first names")
	cmd.Flags().StringVar(&bodyBenefits, "benefits", "", "Participation benefits (used in consent)")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "Study description")
	cmd.Flags().StringVar(&bodyInstitution, "institution", "", "Institutional affiliation")
	cmd.Flags().StringVar(&bodyLanguage, "language", "English", "Primary interview language")
	cmd.Flags().StringVar(&bodyMaxResponses, "max-responses", "", "Response quota (null = unlimited)")
	cmd.Flags().StringVar(&bodyMethodology, "methodology", "", "Methodology notes")
	cmd.Flags().StringVar(&bodyModelTier, "model-tier", "open_weights", "Interview model tier: open_weights, standard, or premium ('frontier' is accepted as a deprecated alias for 'premium').")
	cmd.Flags().StringVar(&bodyName, "name", "", "Study name shown to participants")
	cmd.Flags().StringVar(&bodyObjectives, "objectives", "", "Research objectives")
	cmd.Flags().StringVar(&bodyProjectId, "project-id", "", "Project to create the study in. The caller must belong to the organization that owns this project.")
	cmd.Flags().StringVar(&bodyRedirectUrl, "redirect-url", "", "URL participants are sent to after completing.")
	cmd.Flags().StringVar(&bodyResearchQuestion, "research-question", "", "The research question(s)")
	cmd.Flags().StringVar(&bodyRisks, "risks", "", "Participation risks (used in consent)")
	cmd.Flags().StringVar(&bodySupportContact, "support-contact", "", "Researcher/support contact")
	cmd.Flags().StringVar(&bodySurveyType, "survey-type", "sociology", "Study methodology. One of: sociology, user_experience, customer_development, polling")
	cmd.Flags().StringVar(&bodyTargetPopulation, "target-population", "", "Target participant population")
	cmd.Flags().BoolVar(&bodyVideoEnabled, "video-enabled", false, "Offer a video-call interview link alongside text chat")
	cmd.Flags().BoolVar(&bodyVoiceEnabled, "voice-enabled", false, "Offer a voice-call interview link alongside text chat")
	cmd.Flags().BoolVar(&stdinBody, "stdin", false, "Read request body as JSON from stdin")

	return cmd
}
