// Copyright 2026 francis and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newWebhooksDeliveriesListWebhookCmd(flags *rootFlags) *cobra.Command {
	var flagEventType string
	var flagSuccess string
	var flagExternalParticipantId string
	var flagLimit int
	var flagOffset string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "list-webhook <webhook_id>",
		Aliases:     []string{"get"},
		Short:       "The delivery log for one endpoint, newest first: what was sent, who it was about, the status your server returned",
		Example:     "  deutero-pp-cli webhooks deliveries list-webhook 9ca6a913-54ff-495d-92f0-2baaa24ee9c6",
		Annotations: map[string]string{"pp:endpoint": "deliveries.list-webhook", "pp:method": "GET", "pp:path": "/api/v1/webhooks/{webhook_id}/deliveries", "mcp:read-only": "true", "pp:happy-args": "webhook_id=9ca6a913-54ff-495d-92f0-2baaa24ee9c6"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				// A missing required positional is a usage error in every output
				// mode (matches command_promoted.go.tmpl). Machine callers
				// (--json/--agent) also get a JSON error envelope on stdout;
				// usageErr sets exit 2.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "missing required argument",
						"usage": fmt.Sprintf("%s%s", cmd.CommandPath(), " <webhook_id>"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("missing required argument\nUsage: %s%s", cmd.CommandPath(), " <webhook_id>"))
			}
			path := "/api/v1/webhooks/{webhook_id}/deliveries"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("webhook_id is required\nUsage: %s <%s>", cmd.CommandPath(), "webhook_id"))
			}
			path = replacePathParam(path, "webhook_id", args[0])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			data, prov, err := resolvePaginatedReadWithStrategy(cmd.Context(), c, flags, "live", "deliveries", path, retainCLIQueryParams(cmd, map[string]string{
				"event_type":              formatCLIParamValue(flagEventType),
				"success":                 formatCLIParamValue(flagSuccess),
				"external_participant_id": formatCLIParamValue(flagExternalParticipantId),
				"limit":                   formatCLIParamValue(flagLimit),
				"offset":                  formatCLIParamValue(flagOffset),
			}, map[string][]string{"event_type": {"event-type"}, "success": {"success"}, "external_participant_id": {"external-participant-id"}, "limit": {"limit"}, "offset": {"offset"}}, "offset", "offset"), nil, flagAll, "offset", "offset", "limit", 50, "", "", "deliveries", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := collectionItemsForOutput(data, path)
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(outputData, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				var selectErr error
				filtered := data
				if flags.selectFields != "" {
					filtered, selectErr = filterFieldsChecked(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered, map[string]bool{"created_at": true, "external_participant_id": true, "id": true, "msg_id": true, "status_code": true})
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				wrapped, wrapErr = wrapPlatformStructuredOutput(wrapped, flags, "results", true)
				if wrapErr != nil {
					return wrapErr
				}
				if err := printOutput(cmd.OutOrStdout(), wrapped, true); err != nil {
					return err
				}
				return selectErr
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, map[string]bool{"created_at": true, "external_participant_id": true, "id": true, "msg_id": true, "status_code": true})
		},
	}
	cmd.Flags().StringVar(&flagEventType, "event-type", "", "Only deliveries of this event type")
	cmd.Flags().StringVar(&flagSuccess, "success", "", "true = only successes, false = only failures")
	cmd.Flags().StringVar(&flagExternalParticipantId, "external-participant-id", "", "Only deliveries carrying this participant id of yours.")
	cmd.Flags().IntVar(&flagLimit, "limit", 50, "Limit")
	cmd.Flags().StringVar(&flagOffset, "offset", "0", "Offset")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	return cmd
}
