// Copyright 2026 francis and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newWebhooksCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "webhooks",
		Short:       "Organization-level event subscriptions: signed HTTP callbacks for interview, analysis, simulation",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newWebhooksCreateCmd(flags))
	cmd.AddCommand(newWebhooksDeleteCmd(flags))
	cmd.AddCommand(newWebhooksListCmd(flags))
	cmd.AddCommand(newWebhooksListEventTypesCmd(flags))
	cmd.AddCommand(newWebhooksUpdateCmd(flags))
	cmd.AddCommand(newWebhooksDeliveriesCmd(flags))
	cmd.AddCommand(newWebhooksRotateSecretCmd(flags))
	return cmd
}
