// Copyright 2026 francis and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// whichEntry is one row of the curated capability index. The index is seeded
// at generation time from novel hero features first, then promoted endpoint
// commands, deduped by Command so a novel that replaced a promoted leaf keeps
// the hero copy.
type whichEntry struct {
	Command      string `json:"command"`
	Description  string `json:"description"`
	Group        string `json:"group,omitempty"`
	WhyItMatters string `json:"why_it_matters,omitempty"`
}

// whichIndex is the curated list of capabilities this CLI advertises.
// Novel hero features come first (declaration-order ties); promoted
// endpoint commands follow so natural-language queries can find them.
var whichIndex = []whichEntry{
	{Command: "flow coverage", Description: "Shows how an Interview Flow actually routed across a whole study: every branch arm's share, how often the otherwise path fired, classifier errors, which steps interviews reached, and which declared variables are being captured. Flow-mode studies only: a linear study has no branch or flow records and correctly returns nothing.", Group: "Flow behavior you cannot see upstream", WhyItMatters: "Reach for this when a branching interview might be misrouting: it names the arms that never fired and the share that fell through to the default, instead of making you read transcripts one at a time."},
	{Command: "reconcile", Description: "Finds participants who completed a study but were never successfully notified, by joining completed interviews against the webhook deliveries that were supposed to tell your system about them.", Group: "Agent-native plumbing", WhyItMatters: "Reach for this after a payout or reward run to find the people your system was never told about, instead of trusting that every webhook landed."},
	{Command: "study diff", Description: "Compares two complete study definitions field by field — details, welcome and translations, screening, characteristics, questions or flow, recruitment — or compares a live study against a saved bundle file.", Group: "Agent-native plumbing", WhyItMatters: "Use this before replaying a bundle over an existing study, or to see exactly how two studies' instruments differ."},
	{Command: "answers matrix", Description: "Turns a study into a real table: one row per interview, one column per question or captured variable, with the external participant id as the join key and optional participant characteristic columns via --with-characteristics. Works for both linear and flow studies.", Group: "Answers the API cannot assemble", WhyItMatters: "Use this when you need to count or correlate answers rather than read them — it produces the rectangle you would otherwise rebuild by hand from transcripts."},
	{Command: "flow effects", Description: "Aggregates what a flow's side steps actually did across a study: failed data fetches with status codes, undelivered signals, and dry-run signals from simulations kept separate from real ones. Flow-mode studies only: a linear study has no branch or flow records and correctly returns nothing.", Group: "Flow behavior you cannot see upstream", WhyItMatters: "Reach for this when an interview-time webhook or data fetch looks unreliable and you need the failures grouped by step rather than buried per interview."},
	{Command: "study bundle", Description: "Snapshots an entire study definition — details, welcome and translations, screening, characteristics, questions or flow, recruitment — into one file. The write half is a separate command, 'study apply --file <f>', which plans by default and writes only with --confirm, and which replays whole-resource sections only (question lists replay via 'studies questions').", Group: "Agent-native plumbing", WhyItMatters: "Use this to clone or version a study definition instead of re-deriving fifteen calls; pair it with 'study diff' to see what a replay would change before running 'study apply --confirm'."},
	{Command: "rehearse diff", Description: "Compares the simulated persona cohort against real participants on the same measures: step reach, branch arm mix, variable capture rate, message count and duration. Needs both cohorts; branch and variable measures are flow-mode only.", Group: "Flow behavior you cannot see upstream", WhyItMatters: "Reach for this after fielding starts to check whether real participants behave like the personas you rehearsed on, before trusting the pilot."},
	{Command: "fielding", Description: "Completions per day against the response quota, projecting the date the quota fills.", Group: "Fielding decisions", WhyItMatters: "Use this to answer whether a study will fill by a date, which the totals-only stats endpoint cannot tell you."},
	{Command: "crosstab", Description: "Segments any scale or options question by any participant characteristic, with per-cell counts and per-segment completion rate.", Group: "Answers the API cannot assemble", WhyItMatters: "Use this to answer whether an answer differs by segment — column marginals reconcile against the server's own tallies, so the numbers are checkable."},
	{Command: "saturation", Description: "Counts how many genuinely new terms each successive interview contributes, and marks the point where the curve flattens. A mechanical word-level proxy for new content, not a judgement about meaning.", Group: "Fielding decisions", WhyItMatters: "Reach for this when deciding whether to stop fielding — it shows when additional interviews stopped adding new language, as evidence for that call rather than the call itself."},
	{Command: "credits", Description: "Get credit balance", Group: "credits", WhyItMatters: "Get credit balance"}, // pp:which-promoted
	{Command: "graph", Description: "The configuration schema for every step type an interview flow can contain", Group: "graph", WhyItMatters: "The configuration schema for every step type an interview flow can contain"}, // pp:which-promoted
	{Command: "health", Description: "Liveness check", Group: "health", WhyItMatters: "Liveness check"}, // pp:which-promoted
	{Command: "interviews", Description: "One interview with its screening answers, participant characteristics, embed-widget metadata (with per-key provenance)", Group: "interviews", WhyItMatters: "One interview with its screening answers, participant characteristics, embed-widget metadata (with per-key provenance)"}, // pp:which-promoted
}

// whichMatch pairs an index entry with its ranking score for a query.
// Higher score means stronger match. The ranker is naive (exact token
// then substring then group tag) because 20-40 entries do not need
// semantic retrieval - a ranker upgrade is a future change that would
// not break this contract.
type whichMatch struct {
	Entry whichEntry `json:"entry"`
	Score int        `json:"score"`
}

// rankWhich returns up to `limit` best matches for `query` against the
// index, sorted by descending score. Score breakdown:
//
//	+3  exact token match on the command's leaf or full path
//	+2  substring match on the command (any part)
//	+2  substring match on description or why_it_matters
//	+1  per-token match on description or why_it_matters (capped at 3)
//	+1  group tag contains the query as a whole token
//
// Ties break on declaration order in the index. An empty query returns
// every entry at score 0 in declaration order - this is the "list all"
// behavior the skill documents for broad agent discovery.
func rankWhich(index []whichEntry, query string, limit int) []whichMatch {
	if limit <= 0 {
		limit = 3
	}
	q := strings.ToLower(strings.TrimSpace(query))
	if q == "" {
		out := make([]whichMatch, 0, len(index))
		for _, e := range index {
			out = append(out, whichMatch{Entry: e, Score: 0})
		}
		return out
	}
	// Sub-tokenize the query the same way command paths are split, so a
	// pasted hyphenated capability (repos-list-for-authenticated) matches.
	qTokens := whichSubTokens(q)

	scored := make([]whichMatch, 0, len(index))
	for i, e := range index {
		score := whichScoreEntry(e, q, qTokens)
		scored = append(scored, whichMatch{Entry: e, Score: score})
		_ = i
	}

	sort.SliceStable(scored, func(i, j int) bool {
		if scored[i].Score != scored[j].Score {
			return scored[i].Score > scored[j].Score
		}
		// Specificity tie-break: at equal score prefer the command with the
		// fewest capability sub-tokens - the canonical operation over variants
		// carrying extra words the request never used.
		return len(whichSubTokens(strings.ToLower(scored[i].Entry.Command))) <
			len(whichSubTokens(strings.ToLower(scored[j].Entry.Command)))
	})
	// Drop zero-score matches when the query was non-empty; agents
	// branching on exit code rely on "no match" meaning no confidence.
	filtered := scored[:0]
	for _, m := range scored {
		if m.Score > 0 {
			filtered = append(filtered, m)
		}
	}
	if len(filtered) > limit {
		filtered = filtered[:limit]
	}
	return filtered
}

func whichScoreEntry(e whichEntry, query string, qTokens []string) int {
	score := 0
	cmd := strings.ToLower(e.Command)
	// Sub-token split (spaces, hyphens, underscores, slashes): a capability
	// word buried in a hyphenated leaf (repos-list-for-authenticated) must be
	// matchable by the words a human asks with, or every command in a group
	// ties on the group token alone and index order decides the answer.
	cmdTokens := whichSubTokens(cmd)
	commandParts := strings.Fields(cmd)
	leaf := ""
	if len(commandParts) > 0 {
		leaf = commandParts[len(commandParts)-1]
	}
	desc := strings.ToLower(e.Description)
	descTokens := whichSubTokens(desc)
	why := strings.ToLower(e.WhyItMatters)
	whyTokens := whichSubTokens(why)
	group := strings.ToLower(e.Group)

	// Exact token match on the command path (any token). Filler words
	// credit a command only when they are the whole unsplit leaf
	// ("run a" → "a"), not a hyphenated sub-token ("in" vs "check-in").
	for _, qt := range qTokens {
		if whichIncidentalToken(qt) && !whichTokenMatch(qt, leaf) {
			continue
		}
		for _, ct := range cmdTokens {
			if whichTokenMatch(qt, ct) {
				score += 3
				break
			}
		}
	}
	// Substring match on the full command (covers hyphenated leaves).
	// An incidental-only query must still name the whole command or leaf
	// so "in" does not admit "check-in" via the trailing fragment.
	if strings.Contains(cmd, query) {
		if !whichAllIncidental(qTokens) || whichTokenMatch(query, leaf) || whichTokenMatch(query, cmd) {
			score += 2
		}
	}
	// Description and rationale are correlated prose fields. Share the existing
	// per-token cap so repeating the same query in both fields cannot outweigh
	// an exact command match. A rationale-only match needs two tokens or an
	// exact multi-token phrase to avoid promoting incidental prose words.
	descPhrase := strings.Contains(desc, query)
	descCredit := whichFieldCredit(qTokens, descTokens)
	whyCredit := whichFieldCredit(qTokens, whyTokens)
	whyPhrase := len(qTokens) > 1 && strings.Contains(why, query)
	if score == 0 && whyCredit < 2 && !whyPhrase {
		whyCredit = 0
	}
	if descPhrase || whyPhrase {
		score += 2
	}
	if whyCredit > descCredit {
		score += whyCredit
	} else {
		score += descCredit
	}
	// Group tag match requires a whole token, not an arbitrary substring.
	// Filler words credit a group only when they are the whole group name.
	groupTokens := whichSubTokens(group)
	groupMatched := false
	for _, qt := range qTokens {
		if whichIncidentalToken(qt) && !whichTokenMatch(qt, group) {
			continue
		}
		for _, gt := range groupTokens {
			if whichTokenMatch(qt, gt) {
				score += 1
				groupMatched = true
				break
			}
		}
		if groupMatched {
			break
		}
	}
	// Possessive aliasing: "my/mine/me/current" in a request is API-speak for
	// the authenticated caller; commands scoped to the authenticated user must
	// outrank generic listings for possessive asks.
	possessive := false
	for _, qt := range qTokens {
		switch qt {
		case "my", "mine", "me", "current":
			possessive = true
		}
	}
	if possessive {
		for _, ct := range cmdTokens {
			if ct == "authenticated" || ct == "me" {
				score += 3
				break
			}
		}
	}
	// Read-intent default: penalize write-verb commands when the request never
	// asked for a write, so neutral asks can never rank a destructive command
	// first on a tie.
	if score > 0 {
		queryWrite := false
		for _, qt := range qTokens {
			if whichWriteVerbs[qt] {
				queryWrite = true
				break
			}
		}
		if !queryWrite {
			for _, ct := range cmdTokens {
				if whichWriteVerbs[ct] {
					score -= 2
					break
				}
			}
		}
	}
	// Specificity: a command leaf carrying capability sub-tokens the request never
	// used is a variant, not the canonical answer ("activity-list-repos-
	// starred-by-authenticated" for a repositories ask). Parent resource tokens
	// are excluded so a valid nested command is not erased by its path. A
	// single-token leaf has no variant to disambiguate; the penalty may still
	// down-rank it but must not zero a description/path hit by itself.
	if score > 0 && len(qTokens) > 1 {
		leafTokens := whichSubTokens(leaf)
		unmatched := 0
		for _, ct := range leafTokens {
			hit := false
			for _, qt := range qTokens {
				if whichTokenMatch(qt, ct) {
					hit = true
					break
				}
			}
			if !hit {
				unmatched++
			}
		}
		if unmatched > 3 {
			unmatched = 3
		}
		if len(leafTokens) < 2 && unmatched >= score {
			unmatched = score - 1
		}
		score -= unmatched
	}
	return score
}

func whichFieldCredit(qTokens, fieldTokens []string) int {
	credit := 0
	matched := make(map[string]struct{})
	for _, qt := range qTokens {
		if whichIncidentalToken(qt) {
			continue
		}
		for _, ft := range fieldTokens {
			if whichTokenMatch(qt, ft) {
				key := whichTokenKey(ft)
				if _, ok := matched[key]; ok {
					break
				}
				matched[key] = struct{}{}
				credit++
				break
			}
		}
		if credit == 3 {
			break
		}
	}
	return credit
}

func whichTokenKey(token string) string {
	token = strings.Trim(strings.ToLower(token), ".,:;!?()[]{}\"'")
	if alias := whichTokenAliases[token]; alias != "" {
		return alias
	}
	return whichSingular(token)
}

func whichTokenMatch(a, b string) bool {
	a = strings.Trim(strings.ToLower(a), ".,:;!?()[]{}\"'")
	b = strings.Trim(strings.ToLower(b), ".,:;!?()[]{}\"'")
	if a == "" || b == "" {
		return false
	}
	if a == b {
		return true
	}
	if whichSingular(a) == whichSingular(b) {
		return true
	}
	return whichTokenAliases[a] != "" && whichTokenAliases[a] == whichTokenAliases[b]
}

func whichSubTokens(cmd string) []string {
	return strings.FieldsFunc(cmd, func(r rune) bool {
		return r == ' ' || r == '-' || r == '_' || r == '/'
	})
}

func whichIncidentalToken(token string) bool {
	token = strings.Trim(strings.ToLower(token), ".,:;!?()[]{}\"'")
	if token == "" {
		return true
	}
	return whichIncidentalTokens[token]
}

func whichAllIncidental(qTokens []string) bool {
	if len(qTokens) == 0 {
		return false
	}
	for _, qt := range qTokens {
		if !whichIncidentalToken(qt) {
			return false
		}
	}
	return true
}

// The closed API-verb set for write-shaped commands. A request that never
// asked for a write must not tie-break into a destructive command.
var whichWriteVerbs = map[string]bool{
	"delete": true, "remove": true, "update": true, "create": true, "set": true,
	"add": true, "replace": true, "rename": true, "transfer": true, "merge": true,
	"lock": true, "unlock": true, "star": true, "unstar": true, "follow": true,
	"unfollow": true, "block": true, "unblock": true, "mute": true, "archive": true,
	"unarchive": true, "cancel": true, "send": true, "upload": true, "subscribe": true,
	"unsubscribe": true, "dismiss": true, "approve": true, "decline": true,
	"post": true, "put": true, "write": true, "edit": true, "modify": true,
	"publish": true, "share": true, "comment": true, "grant": true, "revoke": true,
}

var whichTokenAliases = map[string]string{
	"repo": "repository", "repos": "repository", "repository": "repository", "repositories": "repository",
}

// Filler words that must not create a which match by themselves. Possessive
// aliases (my/mine/me/current) stay significant so authenticated-scoped
// commands can still outrank generic listings.
var whichIncidentalTokens = map[string]bool{
	"a": true, "an": true, "the": true, "i": true,
	"is": true, "are": true, "was": true, "were": true, "be": true, "been": true, "being": true,
	"of": true, "to": true, "in": true, "on": true, "at": true, "for": true, "with": true, "from": true, "by": true, "about": true,
	"what": true, "which": true, "who": true, "whom": true, "whose": true, "how": true, "when": true, "why": true, "where": true,
	"will": true, "would": true, "could": true, "should": true, "may": true, "might": true, "can": true, "shall": true,
	"do": true, "does": true, "did": true, "have": true, "has": true, "had": true,
	"and": true, "or": true, "but": true, "if": true, "then": true, "than": true,
	"this": true, "that": true, "these": true, "those": true, "it": true, "its": true,
}

func whichSingular(s string) string {
	if len(s) > 3 && strings.HasSuffix(s, "ies") {
		return strings.TrimSuffix(s, "ies") + "y"
	}
	if len(s) > 3 && strings.HasSuffix(s, "es") {
		return strings.TrimSuffix(s, "es")
	}
	if len(s) > 2 && strings.HasSuffix(s, "s") {
		return strings.TrimSuffix(s, "s")
	}
	return s
}

func newWhichCmd(flags *rootFlags) *cobra.Command {
	var limit int
	cmd := &cobra.Command{
		Use:   "which [query]",
		Short: "Find the command that implements a capability",
		Annotations: map[string]string{
			"mcp:read-only":       "true",
			"pp:typed-exit-codes": "0,2",
		},
		Long: `which resolves a natural-language capability query (for example, "search messages" or "stale tickets") to the best matching command from this CLI's curated feature index.

Exit codes:
  0  at least one match found
  2  no confident match - the query did not score against any indexed capability; fall back to '--help' or 'search' if this CLI has one. Machine output (--json/--csv/--plain/--quiet, or a pipe) still exits 2 and writes {"matches":[]} (or the equivalent empty table) to stdout.`,
		SilenceUsage: true,
		Example: `  deutero-pp-cli which "stale tickets"
  deutero-pp-cli which "bottleneck"
  deutero-pp-cli which --limit 1 "send message"
  deutero-pp-cli which                                # list the full capability index`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(whichIndex) == 0 {
				return usageErr(fmt.Errorf("this CLI has no curated capability index; run '--help' to see every command"))
			}
			query := strings.Join(args, " ")
			matches := rankWhich(whichIndex, query, limit)

			// Empty query returns the whole index at score 0 (listing mode).
			if strings.TrimSpace(query) == "" {
				return renderWhich(cmd, flags, rankWhichAll(whichIndex))
			}

			if len(matches) == 0 {
				// Machine output still uses the typed exit-2 no-match path.
				// --json (and piped auto-JSON) emit {"matches":[]} on stdout
				// so agents can branch on the envelope without treating exit 0
				// as success. Human terminals keep the usage error only.
				asJSON := flags.asJSON
				if !asJSON && !isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain {
					asJSON = true
				}
				if asJSON || flags.csv || flags.plain || flags.quiet {
					outputFlags := *flags
					outputFlags.asJSON = asJSON || flags.asJSON
					if err := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"matches": []whichMatch{},
					}, &outputFlags); err != nil {
						return err
					}
				}
				return usageErr(fmt.Errorf("no match for %q; try '%s --help' for the full command list", query, cmd.Root().Name()))
			}
			return renderWhich(cmd, flags, matches)
		},
	}
	cmd.Flags().IntVar(&limit, "limit", 3, "Maximum number of matches to return")
	return cmd
}

// rankWhichAll is a narrow helper used by the "empty query lists the
// index" path. It returns every entry in declaration order at score 0
// so the render path treats them uniformly.
func rankWhichAll(index []whichEntry) []whichMatch {
	out := make([]whichMatch, 0, len(index))
	for _, e := range index {
		out = append(out, whichMatch{Entry: e, Score: 0})
	}
	return out
}

func renderWhich(cmd *cobra.Command, flags *rootFlags, matches []whichMatch) error {
	w := cmd.OutOrStdout()
	// Output shape follows the same rule as every other generated
	// command: JSON when the caller asked for it OR when stdout is not
	// a terminal; table when a human is looking.
	asJSON := flags.asJSON
	if !asJSON && !isTerminal(w) {
		asJSON = true
	}
	if asJSON {
		// JSON envelope: {matches: [...]}. The wrap is critical:
		// printJSONFiltered's --compact path uses compactListFields
		// (allowlist) for top-level arrays, which would strip
		// entry/score keys; routing through compactObjectFields
		// (blocklist) via an object envelope preserves them.
		if matches == nil {
			matches = []whichMatch{}
		}
		return printJSONFiltered(w, map[string]any{"matches": matches}, flags)
	}
	fmt.Fprintf(w, "%-24s  %-8s  %s\n", "COMMAND", "SCORE", "DESCRIPTION")
	for _, m := range matches {
		fmt.Fprintf(w, "%-24s  %-8d  %s\n", m.Entry.Command, m.Score, m.Entry.Description)
	}
	return nil
}
